; ================================================
;  Generated by Y-Lang Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @String_new(...)
declare ptr @File_read_to_string(...)
declare i32 @Lexer_new(...)
declare i32 @Lexer_tokenize(...)
declare i32 @Vec_len(...)
declare void @print(...)
declare i32 @AstArena_new(...)
declare i32 @Parser_new(...)
declare i32 @Parser_parse_program(...)
declare i32 @CEmitter_new(...)
declare i32 @LlvmEmitter_new(...)
declare i32 @CEmitter_emit_func(...)
declare i32 @LlvmEmitter_emit_func(...)
declare void @File_write(...)
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i32)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [36 x i8] c"--- Y-Lang Self-Hosted Compiler ---\00"
@.str.1 = private unnamed_addr constant [8 x i8] c"test.yy\00"
@.str.2 = private unnamed_addr constant [15 x i8] c"Lexed tokens: \00"
@.str.3 = private unnamed_addr constant [1 x i8] c"\00"
@.str.4 = private unnamed_addr constant [7 x i8] c"test.c\00"
@.str.5 = private unnamed_addr constant [8 x i8] c"test.ll\00"
@.str.6 = private unnamed_addr constant [52 x i8] c"Successfully compiled test.yy -> test.c and test.ll\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define void @main() #0 {
entry:
  %source_path = alloca ptr
  %source = alloca ptr
  %lexer = alloca %Lexer
  %tokens = alloca ptr
  %token_count = alloca i64
  %arena = alloca %AstArena
  %p = alloca %Parser
  %emitter = alloca %CEmitter
  %ll_emitter = alloca %LlvmEmitter
  %f = alloca i64
  %func_count = alloca i64
  %out_path = alloca ptr
  %ll_path = alloca ptr
  %t1 = call ptr @ystr_new(ptr @.str.0)
  %t2 = load ptr, ptr %t1
  %t3 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t2)
  %t4 = call ptr @ystr_new(ptr @.str.1)
  %t5 = call ptr @String_new(ptr %t4)
  store ptr %t5, ptr %source_path
  %t6 = load ptr, ptr %source_path
  %t8 = load ptr, ptr %source_path
  %t9 = call ptr @File_read_to_string(ptr %t8)
  store ptr %t9, ptr %source
  %t10 = load ptr, ptr %source
  %t12 = load ptr, ptr %source
  %t13 = call i32 @Lexer_new(ptr %t12)
  ; NOTE: struct type coerce pass-through i32 -> %Lexer
  store %Lexer %t13, ptr %lexer
  %t14 = load %Lexer, ptr %lexer
  %t16 = call i32 @Lexer_tokenize(ptr %lexer)
  %t17 = inttoptr i32 %t16 to ptr
  store ptr %t17, ptr %tokens
  %t18 = load ptr, ptr %tokens
  %t20 = load ptr, ptr %tokens
  %t21 = call i32 @Vec_len(ptr %t20)
  %t22 = sext i32 %t21 to i64
  store i64 %t22, ptr %token_count
  %t23 = call ptr @ystr_new(ptr @.str.2)
  %t24 = load ptr, ptr %t23
  %t25 = call i32 (ptr, ...) @printf(ptr @.fmt.s, ptr %t24)
  %t26 = load i64, ptr %token_count
  %t27 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i64 %t26)
  %t28 = call ptr @ystr_new(ptr @.str.3)
  %t29 = load ptr, ptr %t28
  %t30 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t29)
  %t31 = call i32 @AstArena_new()
  ; NOTE: struct type coerce pass-through i32 -> %AstArena
  store %AstArena %t31, ptr %arena
  %t32 = load ptr, ptr %tokens
  %t33 = load i64, ptr %token_count
  %t34 = call i32 @Parser_new(ptr %t32, i64 %t33)
  ; NOTE: struct type coerce pass-through i32 -> %Parser
  store %Parser %t34, ptr %p
  %t35 = load %Parser, ptr %p
  %t37 = load %AstArena, ptr %arena
  %t39 = call i32 @Parser_parse_program(ptr %p, ptr %arena)
  %t40 = call i32 @CEmitter_new()
  ; NOTE: struct type coerce pass-through i32 -> %CEmitter
  store %CEmitter %t40, ptr %emitter
  %t41 = call i32 @LlvmEmitter_new()
  ; NOTE: struct type coerce pass-through i32 -> %LlvmEmitter
  store %LlvmEmitter %t41, ptr %ll_emitter
  %t42 = sext i32 0 to i64
  store i64 %t42, ptr %f
  ; lvalue .funcs
  %t43 = getelementptr %AstArena, ptr %arena, i32 0, i32 0
  %t44 = load i32, ptr %t43
  ; lvalue .funcs
  %t46 = getelementptr %AstArena, ptr %arena, i32 0, i32 0
  %t47 = call i32 @Vec_len(ptr %t46)
  %t48 = sext i32 %t47 to i64
  store i64 %t48, ptr %func_count
  br label %while.cond.1
while.cond.1:
  %t49 = load i64, ptr %f
  %t50 = load i64, ptr %func_count
  %t51 = icmp slt i64 %t49, %t50
  br i1 %t51, label %while.body.2, label %while.end.3
while.body.2:
  %t52 = load %CEmitter, ptr %emitter
  %t54 = load %AstArena, ptr %arena
  %t56 = load i64, ptr %f
  %t57 = call i32 @CEmitter_emit_func(ptr %emitter, ptr %arena, i64 %t56)
  %t58 = load %LlvmEmitter, ptr %ll_emitter
  %t60 = load %AstArena, ptr %arena
  %t62 = load i64, ptr %f
  %t63 = call i32 @LlvmEmitter_emit_func(ptr %ll_emitter, ptr %arena, i64 %t62)
  %t64 = load i64, ptr %f
  %t65 = add i64 %t64, 1
  store i64 %t65, ptr %f
  br label %while.cond.1
while.end.3:
  %t66 = call ptr @ystr_new(ptr @.str.4)
  %t67 = call ptr @String_new(ptr %t66)
  store ptr %t67, ptr %out_path
  %t68 = load ptr, ptr %out_path
  %t70 = load ptr, ptr %out_path
  ; lvalue .c_buffer
  %t71 = getelementptr %CEmitter, ptr %emitter, i32 0, i32 0
  %t72 = load i32, ptr %t71
  ; lvalue .c_buffer
  %t74 = getelementptr %CEmitter, ptr %emitter, i32 0, i32 0
  call void @File_write(ptr %t70, ptr %t74)
  %t76 = call ptr @ystr_new(ptr @.str.5)
  %t77 = call ptr @String_new(ptr %t76)
  store ptr %t77, ptr %ll_path
  %t78 = load ptr, ptr %ll_path
  %t80 = load ptr, ptr %ll_path
  ; lvalue .buffer
  %t81 = getelementptr %LlvmEmitter, ptr %ll_emitter, i32 0, i32 0
  %t82 = load i32, ptr %t81
  ; lvalue .buffer
  %t84 = getelementptr %LlvmEmitter, ptr %ll_emitter, i32 0, i32 0
  call void @File_write(ptr %t80, ptr %t84)
  %t86 = call ptr @ystr_new(ptr @.str.6)
  %t87 = load ptr, ptr %t86
  %t88 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t87)
  ret void
}

!0 = !{i32 1}
