/* ============================================== */
/*  Generated by Y-Lang Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y-Lang Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const char* other) {
    size_t olen = strlen(other);
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y-Lang Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y-Lang Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y-Lang Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const char* path, const YStr* content) {
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t factorial(int32_t n) {
    if ((n <= 1)) {
        return 1;
    }
    return (n * factorial((n - 1)));
}

void fizzbuzz(int32_t n) {
    int32_t i = 1;
    while ((i <= n)) {
        if (((i % 15) == 0)) {
            printf("%s\n", (ystr_new("FizzBuzz")).data);
        } else         if (((i % 3) == 0)) {
            printf("%s\n", (ystr_new("Fizz")).data);
        } else         if (((i % 5) == 0)) {
            printf("%s\n", (ystr_new("Buzz")).data);
        } else {
            printf("%d\n", (int)i);
        }
        i += 1;
    }
}

void main(void) {
    int32_t result = add(3, 4);
    printf("%d\n", (int)result);
    int32_t fact = factorial(10);
    printf("%d\n", (int)fact);
    fizzbuzz(20);
    return;
}

