; ================================================
;  Generated by Y-Lang Compiler — LLVM IR Backend
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [9 x i8] c"FizzBuzz\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"Fizz\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"Buzz\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define i32 @add(i32 %a.arg, i32 %b.arg) {
entry:
  %a = alloca i32
  store i32 %a.arg, ptr %a
  %b = alloca i32
  store i32 %b.arg, ptr %b
  %t1 = load i32, ptr %a
  %t2 = load i32, ptr %b
  %t3 = add i32 %t1, %t2
  ret i32 %t3
}

define i32 @factorial(i32 %n.arg) {
entry:
  %n = alloca i32
  store i32 %n.arg, ptr %n
  %t1 = load i32, ptr %n
  %t2 = icmp sle i32 %t1, 1
  br i1 %t2, label %then.1, label %merge.3
then.1:
  ret i32 1
merge.3:
  %t3 = load i32, ptr %n
  %t4 = load i32, ptr %n
  %t5 = sub i32 %t4, 1
  %t6 = call i32 @factorial(i32 %t5)
  %t7 = mul i32 %t3, %t6
  ret i32 %t7
}

define void @fizzbuzz(i32 %n.arg) {
entry:
  %n = alloca i32
  store i32 %n.arg, ptr %n
  %i = alloca i32
  store i32 1, ptr %i
  br label %while.cond.4
while.cond.4:
  %t1 = load i32, ptr %i
  %t2 = load i32, ptr %n
  %t3 = icmp sle i32 %t1, %t2
  br i1 %t3, label %while.body.5, label %while.end.6
while.body.5:
  %t4 = load i32, ptr %i
  %t5 = srem i32 %t4, 15
  %t6 = icmp eq i32 %t5, 0
  br i1 %t6, label %then.7, label %else.8
then.7:
  %t7 = call ptr @ystr_new(ptr @.str.0)
  %t8 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t7)
  br label %merge.9
else.8:
  %t9 = load i32, ptr %i
  %t10 = srem i32 %t9, 3
  %t11 = icmp eq i32 %t10, 0
  br i1 %t11, label %then.10, label %else.11
then.10:
  %t12 = call ptr @ystr_new(ptr @.str.1)
  %t13 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t12)
  br label %merge.12
else.11:
  %t14 = load i32, ptr %i
  %t15 = srem i32 %t14, 5
  %t16 = icmp eq i32 %t15, 0
  br i1 %t16, label %then.13, label %else.14
then.13:
  %t17 = call ptr @ystr_new(ptr @.str.2)
  %t18 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t17)
  br label %merge.15
else.14:
  %t19 = load i32, ptr %i
  %t20 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i32 %t19)
  br label %merge.15
merge.15:
  br label %merge.12
merge.12:
  br label %merge.9
merge.9:
  %t21 = load i32, ptr %i
  %t22 = add i32 %t21, 1
  store i32 %t22, ptr %i
  br label %while.cond.4
while.end.6:
  ret void
}

define void @main() {
entry:
  %result = alloca i32
  %t1 = call i32 @add(i32 3, i32 4)
  store i32 %t1, ptr %result
  %t2 = load i32, ptr %result
  %t3 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i32 %t2)
  %fact = alloca i32
  %t4 = call i32 @factorial(i32 10)
  store i32 %t4, ptr %fact
  %t5 = load i32, ptr %fact
  %t6 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i32 %t5)
  %t7 = call i32 @fizzbuzz(i32 20)
  ret void
}

