/* ============================================== */
/*  Generated by Y-Lang Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y-Lang Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y-Lang Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y-Lang Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y-Lang Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


typedef struct Token Token;
typedef struct Lexer Lexer;

struct Token {
    TokenKind kind;
    size_t line;
    size_t col;
    YStr lexeme;
};

struct Lexer {
    YVec input;
    size_t pos;
    size_t line;
    size_t col;
};

typedef enum {
    TokenKind_TAG_Kernel,
    TokenKind_TAG_Let,
    TokenKind_TAG_Type,
    TokenKind_TAG_For,
    TokenKind_TAG_In,
    TokenKind_TAG_Step,
    TokenKind_TAG_Return,
    TokenKind_TAG_Const,
    TokenKind_TAG_Pub,
    TokenKind_TAG_Mut,
    TokenKind_TAG_Unsafe,
    TokenKind_TAG_Wait,
    TokenKind_TAG_Emit,
    TokenKind_TAG_Load,
    TokenKind_TAG_Store,
    TokenKind_TAG_Barrier,
    TokenKind_TAG_Struct,
    TokenKind_TAG_Enum,
    TokenKind_TAG_Fn,
    TokenKind_TAG_Match,
    TokenKind_TAG_Safe,
    TokenKind_TAG_Chisel,
    TokenKind_TAG_Import,
    TokenKind_TAG_While,
    TokenKind_TAG_Impl,
    TokenKind_TAG_SelfKw,
    TokenKind_TAG_If,
    TokenKind_TAG_Else,
    TokenKind_TAG_True,
    TokenKind_TAG_False,
    TokenKind_TAG_GlobalMemory,
    TokenKind_TAG_L2Memory,
    TokenKind_TAG_SharedMemory,
    TokenKind_TAG_RegisterFile,
    TokenKind_TAG_SmemLayout,
    TokenKind_TAG_Swizzle,
    TokenKind_TAG_NoSwizzle,
    TokenKind_TAG_Pipeline,
    TokenKind_TAG_Transfer,
    TokenKind_TAG_Fragment,
    TokenKind_TAG_MmaMod,
    TokenKind_TAG_RoleA,
    TokenKind_TAG_RoleB,
    TokenKind_TAG_RoleC,
    TokenKind_TAG_RoleD,
    TokenKind_TAG_F16,
    TokenKind_TAG_BF16,
    TokenKind_TAG_TF32,
    TokenKind_TAG_F32,
    TokenKind_TAG_F64,
    TokenKind_TAG_I8,
    TokenKind_TAG_I16,
    TokenKind_TAG_I32,
    TokenKind_TAG_I64,
    TokenKind_TAG_U3,
    TokenKind_TAG_U8,
    TokenKind_TAG_U16,
    TokenKind_TAG_U32,
    TokenKind_TAG_U64,
    TokenKind_TAG_Bool,
    TokenKind_TAG_StringTy,
    TokenKind_TAG_CharTy,
    TokenKind_TAG_VecTy,
    TokenKind_TAG_File,
    TokenKind_TAG_OptionTy,
    TokenKind_TAG_Async,
    TokenKind_TAG_Sync,
    TokenKind_TAG_L2Persist,
    TokenKind_TAG_L2EvictFirst,
    TokenKind_TAG_L2EvictLast,
    TokenKind_TAG_L2Stream,
    TokenKind_TAG_HardwareTarget,
    TokenKind_TAG_CpAsync,
    TokenKind_TAG_LdMatrix,
    TokenKind_TAG_MmaSync,
    TokenKind_TAG_BarrierSync,
    TokenKind_TAG_AtTarget,
    TokenKind_TAG_AtCachePolicy,
    TokenKind_TAG_AtPtxEmit,
    TokenKind_TAG_AtAvxEmit,
    TokenKind_TAG_AtInline,
    TokenKind_TAG_AtNoInline,
    TokenKind_TAG_AtAlign,
    TokenKind_TAG_AtSafe,
    TokenKind_TAG_AtUnsafe,
    TokenKind_TAG_AtGpuUncached,
    TokenKind_TAG_AtAtomic,
    TokenKind_TAG_AtStaticAssert,
    TokenKind_TAG_AtUnknown,
    TokenKind_TAG_Arrow,
    TokenKind_TAG_DotDot,
    TokenKind_TAG_ColonColon,
    TokenKind_TAG_Colon,
    TokenKind_TAG_Assign,
    TokenKind_TAG_FatArrow,
    TokenKind_TAG_EqEq,
    TokenKind_TAG_NotEq,
    TokenKind_TAG_Lt,
    TokenKind_TAG_Gt,
    TokenKind_TAG_LtEq,
    TokenKind_TAG_GtEq,
    TokenKind_TAG_Plus,
    TokenKind_TAG_Minus,
    TokenKind_TAG_Star,
    TokenKind_TAG_Slash,
    TokenKind_TAG_Percent,
    TokenKind_TAG_Ampersand,
    TokenKind_TAG_Pipe,
    TokenKind_TAG_Caret,
    TokenKind_TAG_Bang,
    TokenKind_TAG_AmpAmp,
    TokenKind_TAG_PipePipe,
    TokenKind_TAG_LtLt,
    TokenKind_TAG_GtGt,
    TokenKind_TAG_PlusAssign,
    TokenKind_TAG_MinusAssign,
    TokenKind_TAG_StarAssign,
    TokenKind_TAG_SlashAssign,
    TokenKind_TAG_Dot,
    TokenKind_TAG_LBrace,
    TokenKind_TAG_RBrace,
    TokenKind_TAG_LParen,
    TokenKind_TAG_RParen,
    TokenKind_TAG_LBracket,
    TokenKind_TAG_RBracket,
    TokenKind_TAG_Semicolon,
    TokenKind_TAG_Comma,
    TokenKind_TAG_IntLit,
    TokenKind_TAG_FloatLit,
    TokenKind_TAG_StringLit,
    TokenKind_TAG_CharLit,
    TokenKind_TAG_Ident,
    TokenKind_TAG_Eof,
    TokenKind_TAG_Unknown
} TokenKind_Tag;

typedef struct {
    YStr _0;
} TokenKind_MmaMod_Data;

typedef struct {
    YStr _0;
} TokenKind_HardwareTarget_Data;

typedef struct {
    YStr _0;
} TokenKind_AtUnknown_Data;

typedef struct {
    int64_t _0;
} TokenKind_IntLit_Data;

typedef struct {
    double _0;
} TokenKind_FloatLit_Data;

typedef struct {
    YStr _0;
} TokenKind_StringLit_Data;

typedef struct {
    char _0;
} TokenKind_CharLit_Data;

typedef struct {
    YStr _0;
} TokenKind_Ident_Data;

typedef struct {
    char _0;
} TokenKind_Unknown_Data;

typedef struct {
    TokenKind_Tag tag;
    union {
        TokenKind_MmaMod_Data MmaMod;
        TokenKind_HardwareTarget_Data HardwareTarget;
        TokenKind_AtUnknown_Data AtUnknown;
        TokenKind_IntLit_Data IntLit;
        TokenKind_FloatLit_Data FloatLit;
        TokenKind_StringLit_Data StringLit;
        TokenKind_CharLit_Data CharLit;
        TokenKind_Ident_Data Ident;
        TokenKind_Unknown_Data Unknown;
    } data;
} TokenKind;

#define TokenKind_Kernel ((TokenKind){ .tag = TokenKind_TAG_Kernel })
#define TokenKind_Let ((TokenKind){ .tag = TokenKind_TAG_Let })
#define TokenKind_Type ((TokenKind){ .tag = TokenKind_TAG_Type })
#define TokenKind_For ((TokenKind){ .tag = TokenKind_TAG_For })
#define TokenKind_In ((TokenKind){ .tag = TokenKind_TAG_In })
#define TokenKind_Step ((TokenKind){ .tag = TokenKind_TAG_Step })
#define TokenKind_Return ((TokenKind){ .tag = TokenKind_TAG_Return })
#define TokenKind_Const ((TokenKind){ .tag = TokenKind_TAG_Const })
#define TokenKind_Pub ((TokenKind){ .tag = TokenKind_TAG_Pub })
#define TokenKind_Mut ((TokenKind){ .tag = TokenKind_TAG_Mut })
#define TokenKind_Unsafe ((TokenKind){ .tag = TokenKind_TAG_Unsafe })
#define TokenKind_Wait ((TokenKind){ .tag = TokenKind_TAG_Wait })
#define TokenKind_Emit ((TokenKind){ .tag = TokenKind_TAG_Emit })
#define TokenKind_Load ((TokenKind){ .tag = TokenKind_TAG_Load })
#define TokenKind_Store ((TokenKind){ .tag = TokenKind_TAG_Store })
#define TokenKind_Barrier ((TokenKind){ .tag = TokenKind_TAG_Barrier })
#define TokenKind_Struct ((TokenKind){ .tag = TokenKind_TAG_Struct })
#define TokenKind_Enum ((TokenKind){ .tag = TokenKind_TAG_Enum })
#define TokenKind_Fn ((TokenKind){ .tag = TokenKind_TAG_Fn })
#define TokenKind_Match ((TokenKind){ .tag = TokenKind_TAG_Match })
#define TokenKind_Safe ((TokenKind){ .tag = TokenKind_TAG_Safe })
#define TokenKind_Chisel ((TokenKind){ .tag = TokenKind_TAG_Chisel })
#define TokenKind_Import ((TokenKind){ .tag = TokenKind_TAG_Import })
#define TokenKind_While ((TokenKind){ .tag = TokenKind_TAG_While })
#define TokenKind_Impl ((TokenKind){ .tag = TokenKind_TAG_Impl })
#define TokenKind_SelfKw ((TokenKind){ .tag = TokenKind_TAG_SelfKw })
#define TokenKind_If ((TokenKind){ .tag = TokenKind_TAG_If })
#define TokenKind_Else ((TokenKind){ .tag = TokenKind_TAG_Else })
#define TokenKind_True ((TokenKind){ .tag = TokenKind_TAG_True })
#define TokenKind_False ((TokenKind){ .tag = TokenKind_TAG_False })
#define TokenKind_GlobalMemory ((TokenKind){ .tag = TokenKind_TAG_GlobalMemory })
#define TokenKind_L2Memory ((TokenKind){ .tag = TokenKind_TAG_L2Memory })
#define TokenKind_SharedMemory ((TokenKind){ .tag = TokenKind_TAG_SharedMemory })
#define TokenKind_RegisterFile ((TokenKind){ .tag = TokenKind_TAG_RegisterFile })
#define TokenKind_SmemLayout ((TokenKind){ .tag = TokenKind_TAG_SmemLayout })
#define TokenKind_Swizzle ((TokenKind){ .tag = TokenKind_TAG_Swizzle })
#define TokenKind_NoSwizzle ((TokenKind){ .tag = TokenKind_TAG_NoSwizzle })
#define TokenKind_Pipeline ((TokenKind){ .tag = TokenKind_TAG_Pipeline })
#define TokenKind_Transfer ((TokenKind){ .tag = TokenKind_TAG_Transfer })
#define TokenKind_Fragment ((TokenKind){ .tag = TokenKind_TAG_Fragment })
static inline TokenKind TokenKind_MmaMod(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_MmaMod;
    res.data.MmaMod._0 = _0;
    return res;
}

#define TokenKind_RoleA ((TokenKind){ .tag = TokenKind_TAG_RoleA })
#define TokenKind_RoleB ((TokenKind){ .tag = TokenKind_TAG_RoleB })
#define TokenKind_RoleC ((TokenKind){ .tag = TokenKind_TAG_RoleC })
#define TokenKind_RoleD ((TokenKind){ .tag = TokenKind_TAG_RoleD })
#define TokenKind_F16 ((TokenKind){ .tag = TokenKind_TAG_F16 })
#define TokenKind_BF16 ((TokenKind){ .tag = TokenKind_TAG_BF16 })
#define TokenKind_TF32 ((TokenKind){ .tag = TokenKind_TAG_TF32 })
#define TokenKind_F32 ((TokenKind){ .tag = TokenKind_TAG_F32 })
#define TokenKind_F64 ((TokenKind){ .tag = TokenKind_TAG_F64 })
#define TokenKind_I8 ((TokenKind){ .tag = TokenKind_TAG_I8 })
#define TokenKind_I16 ((TokenKind){ .tag = TokenKind_TAG_I16 })
#define TokenKind_I32 ((TokenKind){ .tag = TokenKind_TAG_I32 })
#define TokenKind_I64 ((TokenKind){ .tag = TokenKind_TAG_I64 })
#define TokenKind_U3 ((TokenKind){ .tag = TokenKind_TAG_U3 })
#define TokenKind_U8 ((TokenKind){ .tag = TokenKind_TAG_U8 })
#define TokenKind_U16 ((TokenKind){ .tag = TokenKind_TAG_U16 })
#define TokenKind_U32 ((TokenKind){ .tag = TokenKind_TAG_U32 })
#define TokenKind_U64 ((TokenKind){ .tag = TokenKind_TAG_U64 })
#define TokenKind_Bool ((TokenKind){ .tag = TokenKind_TAG_Bool })
#define TokenKind_StringTy ((TokenKind){ .tag = TokenKind_TAG_StringTy })
#define TokenKind_CharTy ((TokenKind){ .tag = TokenKind_TAG_CharTy })
#define TokenKind_VecTy ((TokenKind){ .tag = TokenKind_TAG_VecTy })
#define TokenKind_File ((TokenKind){ .tag = TokenKind_TAG_File })
#define TokenKind_OptionTy ((TokenKind){ .tag = TokenKind_TAG_OptionTy })
#define TokenKind_Async ((TokenKind){ .tag = TokenKind_TAG_Async })
#define TokenKind_Sync ((TokenKind){ .tag = TokenKind_TAG_Sync })
#define TokenKind_L2Persist ((TokenKind){ .tag = TokenKind_TAG_L2Persist })
#define TokenKind_L2EvictFirst ((TokenKind){ .tag = TokenKind_TAG_L2EvictFirst })
#define TokenKind_L2EvictLast ((TokenKind){ .tag = TokenKind_TAG_L2EvictLast })
#define TokenKind_L2Stream ((TokenKind){ .tag = TokenKind_TAG_L2Stream })
static inline TokenKind TokenKind_HardwareTarget(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_HardwareTarget;
    res.data.HardwareTarget._0 = _0;
    return res;
}

#define TokenKind_CpAsync ((TokenKind){ .tag = TokenKind_TAG_CpAsync })
#define TokenKind_LdMatrix ((TokenKind){ .tag = TokenKind_TAG_LdMatrix })
#define TokenKind_MmaSync ((TokenKind){ .tag = TokenKind_TAG_MmaSync })
#define TokenKind_BarrierSync ((TokenKind){ .tag = TokenKind_TAG_BarrierSync })
#define TokenKind_AtTarget ((TokenKind){ .tag = TokenKind_TAG_AtTarget })
#define TokenKind_AtCachePolicy ((TokenKind){ .tag = TokenKind_TAG_AtCachePolicy })
#define TokenKind_AtPtxEmit ((TokenKind){ .tag = TokenKind_TAG_AtPtxEmit })
#define TokenKind_AtAvxEmit ((TokenKind){ .tag = TokenKind_TAG_AtAvxEmit })
#define TokenKind_AtInline ((TokenKind){ .tag = TokenKind_TAG_AtInline })
#define TokenKind_AtNoInline ((TokenKind){ .tag = TokenKind_TAG_AtNoInline })
#define TokenKind_AtAlign ((TokenKind){ .tag = TokenKind_TAG_AtAlign })
#define TokenKind_AtSafe ((TokenKind){ .tag = TokenKind_TAG_AtSafe })
#define TokenKind_AtUnsafe ((TokenKind){ .tag = TokenKind_TAG_AtUnsafe })
#define TokenKind_AtGpuUncached ((TokenKind){ .tag = TokenKind_TAG_AtGpuUncached })
#define TokenKind_AtAtomic ((TokenKind){ .tag = TokenKind_TAG_AtAtomic })
#define TokenKind_AtStaticAssert ((TokenKind){ .tag = TokenKind_TAG_AtStaticAssert })
static inline TokenKind TokenKind_AtUnknown(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_AtUnknown;
    res.data.AtUnknown._0 = _0;
    return res;
}

#define TokenKind_Arrow ((TokenKind){ .tag = TokenKind_TAG_Arrow })
#define TokenKind_DotDot ((TokenKind){ .tag = TokenKind_TAG_DotDot })
#define TokenKind_ColonColon ((TokenKind){ .tag = TokenKind_TAG_ColonColon })
#define TokenKind_Colon ((TokenKind){ .tag = TokenKind_TAG_Colon })
#define TokenKind_Assign ((TokenKind){ .tag = TokenKind_TAG_Assign })
#define TokenKind_FatArrow ((TokenKind){ .tag = TokenKind_TAG_FatArrow })
#define TokenKind_EqEq ((TokenKind){ .tag = TokenKind_TAG_EqEq })
#define TokenKind_NotEq ((TokenKind){ .tag = TokenKind_TAG_NotEq })
#define TokenKind_Lt ((TokenKind){ .tag = TokenKind_TAG_Lt })
#define TokenKind_Gt ((TokenKind){ .tag = TokenKind_TAG_Gt })
#define TokenKind_LtEq ((TokenKind){ .tag = TokenKind_TAG_LtEq })
#define TokenKind_GtEq ((TokenKind){ .tag = TokenKind_TAG_GtEq })
#define TokenKind_Plus ((TokenKind){ .tag = TokenKind_TAG_Plus })
#define TokenKind_Minus ((TokenKind){ .tag = TokenKind_TAG_Minus })
#define TokenKind_Star ((TokenKind){ .tag = TokenKind_TAG_Star })
#define TokenKind_Slash ((TokenKind){ .tag = TokenKind_TAG_Slash })
#define TokenKind_Percent ((TokenKind){ .tag = TokenKind_TAG_Percent })
#define TokenKind_Ampersand ((TokenKind){ .tag = TokenKind_TAG_Ampersand })
#define TokenKind_Pipe ((TokenKind){ .tag = TokenKind_TAG_Pipe })
#define TokenKind_Caret ((TokenKind){ .tag = TokenKind_TAG_Caret })
#define TokenKind_Bang ((TokenKind){ .tag = TokenKind_TAG_Bang })
#define TokenKind_AmpAmp ((TokenKind){ .tag = TokenKind_TAG_AmpAmp })
#define TokenKind_PipePipe ((TokenKind){ .tag = TokenKind_TAG_PipePipe })
#define TokenKind_LtLt ((TokenKind){ .tag = TokenKind_TAG_LtLt })
#define TokenKind_GtGt ((TokenKind){ .tag = TokenKind_TAG_GtGt })
#define TokenKind_PlusAssign ((TokenKind){ .tag = TokenKind_TAG_PlusAssign })
#define TokenKind_MinusAssign ((TokenKind){ .tag = TokenKind_TAG_MinusAssign })
#define TokenKind_StarAssign ((TokenKind){ .tag = TokenKind_TAG_StarAssign })
#define TokenKind_SlashAssign ((TokenKind){ .tag = TokenKind_TAG_SlashAssign })
#define TokenKind_Dot ((TokenKind){ .tag = TokenKind_TAG_Dot })
#define TokenKind_LBrace ((TokenKind){ .tag = TokenKind_TAG_LBrace })
#define TokenKind_RBrace ((TokenKind){ .tag = TokenKind_TAG_RBrace })
#define TokenKind_LParen ((TokenKind){ .tag = TokenKind_TAG_LParen })
#define TokenKind_RParen ((TokenKind){ .tag = TokenKind_TAG_RParen })
#define TokenKind_LBracket ((TokenKind){ .tag = TokenKind_TAG_LBracket })
#define TokenKind_RBracket ((TokenKind){ .tag = TokenKind_TAG_RBracket })
#define TokenKind_Semicolon ((TokenKind){ .tag = TokenKind_TAG_Semicolon })
#define TokenKind_Comma ((TokenKind){ .tag = TokenKind_TAG_Comma })
static inline TokenKind TokenKind_IntLit(int64_t _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_IntLit;
    res.data.IntLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_FloatLit(double _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_FloatLit;
    res.data.FloatLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_StringLit(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_StringLit;
    res.data.StringLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_CharLit(char _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_CharLit;
    res.data.CharLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_Ident(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_Ident;
    res.data.Ident._0 = _0;
    return res;
}

#define TokenKind_Eof ((TokenKind){ .tag = TokenKind_TAG_Eof })
static inline TokenKind TokenKind_Unknown(char _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_Unknown;
    res.data.Unknown._0 = _0;
    return res;
}

Token Token_new(TokenKind kind, size_t line, size_t col, const YStr* lexeme);
Lexer Lexer_new(const YStr* source);
char Lexer_peek(const Lexer* lx);
char Lexer_peek2(const Lexer* lx);
char Lexer_advance(Lexer* lx);
bool Lexer_matches_next(Lexer* lx, char expected);
TokenKind Lexer_classify_ident(const YStr* s);
void Lexer_skip_whitespace(Lexer* lx);
Token Lexer_scan_ident_or_keyword(Lexer* lx, size_t start_col, char first_char);
Token Lexer_scan_number(Lexer* lx, size_t start_col, char first_char);
Token Lexer_next_token(Lexer* lx);
YVec Lexer_tokenize(Lexer* lx);
void main(void);

/* impl Token */
Token Token_new(TokenKind kind, size_t line, size_t col, const YStr* lexeme) {
    Token tok;
    tok.kind = kind;
    tok.line = line;
    tok.col = col;
    tok.lexeme = ystr_clone(lexeme);
    return tok;
}

/* impl Lexer */
Lexer Lexer_new(const YStr* source) {
    Lexer lx;
    YVec input_vec = yvec_new(1);
    size_t len = ystr_len(source);
    size_t i = 0;
    while ((i < len)) {
        char ch = ystr_char_at(source, i);
        { __typeof__(ch) __push_tmp = ch; yvec_push((&input_vec), &__push_tmp); };
        i += 1;
    }
    lx.input = input_vec;
    lx.pos = 0;
    lx.line = 1;
    lx.col = 1;
    return lx;
}

char Lexer_peek(const Lexer* lx) {
    size_t max_len = yvec_len((&(*lx).input));
    if (((*lx).pos >= max_len)) {
        return '\0';
    }
    return yvec_get_char((&(*lx).input), (*lx).pos);
}

char Lexer_peek2(const Lexer* lx) {
    size_t max_len = yvec_len((&(*lx).input));
    if ((((*lx).pos + 1) >= max_len)) {
        return '\0';
    }
    return yvec_get_char((&(*lx).input), ((*lx).pos + 1));
}

char Lexer_advance(Lexer* lx) {
    char ch = Lexer_peek(lx);
    if ((ch == '\0')) {
        return ch;
    }
    (*lx).pos += 1;
    if ((ch == '\n')) {
        (*lx).line += 1;
        (*lx).col = 1;
    } else {
        (*lx).col += 1;
    }
    return ch;
}

bool Lexer_matches_next(Lexer* lx, char expected) {
    char ch = Lexer_peek(lx);
    if ((ch == expected)) {
        Lexer_advance(lx);
        return true;
    }
    return false;
}

/* impl Lexer */
TokenKind Lexer_classify_ident(const YStr* s) {
    if (ystr_eq_cstr(s, "enum")) {
        return TokenKind_Enum;
    }
    if (ystr_eq_cstr(s, "struct")) {
        return TokenKind_Struct;
    }
    if (ystr_eq_cstr(s, "impl")) {
        return TokenKind_Impl;
    }
    if (ystr_eq_cstr(s, "fn")) {
        return TokenKind_Fn;
    }
    if (ystr_eq_cstr(s, "let")) {
        return TokenKind_Let;
    }
    if (ystr_eq_cstr(s, "return")) {
        return TokenKind_Return;
    }
    if (ystr_eq_cstr(s, "if")) {
        return TokenKind_If;
    }
    if (ystr_eq_cstr(s, "else")) {
        return TokenKind_Else;
    }
    if (ystr_eq_cstr(s, "while")) {
        return TokenKind_While;
    }
    if (ystr_eq_cstr(s, "true")) {
        return TokenKind_True;
    }
    if (ystr_eq_cstr(s, "false")) {
        return TokenKind_False;
    }
    if (ystr_eq_cstr(s, "mut")) {
        return TokenKind_Mut;
    }
    if (ystr_eq_cstr(s, "String")) {
        return TokenKind_StringTy;
    }
    if (ystr_eq_cstr(s, "Vec")) {
        return TokenKind_VecTy;
    }
    if (ystr_eq_cstr(s, "char")) {
        return TokenKind_CharTy;
    }
    if (ystr_eq_cstr(s, "usize")) {
        return TokenKind_Ident(ystr_clone(s));
    }
    if (ystr_eq_cstr(s, "I32")) {
        return TokenKind_I32;
    }
    if (ystr_eq_cstr(s, "I64")) {
        return TokenKind_I64;
    }
    if (ystr_eq_cstr(s, "bool")) {
        return TokenKind_Bool;
    }
    return TokenKind_Ident(ystr_clone(s));
}

void Lexer_skip_whitespace(Lexer* lx) {
    bool parsing = true;
    while (parsing) {
        char ch = Lexer_peek(lx);
        if ((ch == ' ')) {
            Lexer_advance(lx);
        } else         if ((ch == '\n')) {
            Lexer_advance(lx);
        } else         if ((ch == '\r')) {
            Lexer_advance(lx);
        } else         if ((ch == '\t')) {
            Lexer_advance(lx);
        } else {
            parsing = false;
        }
    }
}

Token Lexer_scan_ident_or_keyword(Lexer* lx, size_t start_col, char first_char) {
    size_t line = (*lx).line;
    YStr s = ystr_new("");
    ystr_push((&s), first_char);
    bool parsing = true;
    while (parsing) {
        char ch = Lexer_peek(lx);
        bool is_alpha = false;
        if ((ch >= 'a')) {
            if ((ch <= 'z')) {
                is_alpha = true;
            }
        }
        if ((ch >= 'A')) {
            if ((ch <= 'Z')) {
                is_alpha = true;
            }
        }
        if ((ch >= '0')) {
            if ((ch <= '9')) {
                is_alpha = true;
            }
        }
        if ((ch == '_')) {
            is_alpha = true;
        }
        if (is_alpha) {
            ystr_push((&s), ch);
            Lexer_advance(lx);
        } else {
            parsing = false;
        }
    }
    TokenKind kind = Lexer_classify_ident((&s));
    return Token_new(kind, line, start_col, (&s));
}

/* impl Lexer */
Token Lexer_scan_number(Lexer* lx, size_t start_col, char first_char) {
    size_t line = (*lx).line;
    YStr s = ystr_new("");
    ystr_push((&s), first_char);
    bool is_float = false;
    bool parsing = true;
    while (parsing) {
        char ch = Lexer_peek(lx);
        bool is_digit = false;
        if ((ch >= '0')) {
            if ((ch <= '9')) {
                is_digit = true;
            }
        }
        if (is_digit) {
            ystr_push((&s), ch);
            Lexer_advance(lx);
        } else         if ((ch == '.')) {
            is_float = true;
            ystr_push((&s), ch);
            Lexer_advance(lx);
        } else {
            parsing = false;
        }
    }
    if (is_float) {
        return Token_new(TokenKind_FloatLit(0.0), line, start_col, (&s));
    } else {
        return Token_new(TokenKind_IntLit(0), line, start_col, (&s));
    }
}

Token Lexer_next_token(Lexer* lx) {
    Lexer_skip_whitespace(lx);
    size_t line = (*lx).line;
    size_t start_col = (*lx).col;
    char ch = Lexer_advance(lx);
    if ((ch == '\0')) {
        YStr empty = ystr_new("");
        return Token_new(TokenKind_Eof, line, start_col, (&empty));
    }
    if ((ch == '{')) {
        YStr x = ystr_new("{");
        return Token_new(TokenKind_LBrace, line, start_col, (&x));
    }
    if ((ch == '}')) {
        YStr x = ystr_new("}");
        return Token_new(TokenKind_RBrace, line, start_col, (&x));
    }
    if ((ch == '(')) {
        YStr x = ystr_new("(");
        return Token_new(TokenKind_LParen, line, start_col, (&x));
    }
    if ((ch == ')')) {
        YStr x = ystr_new(")");
        return Token_new(TokenKind_RParen, line, start_col, (&x));
    }
    if ((ch == ';')) {
        YStr x = ystr_new(";");
        return Token_new(TokenKind_Semicolon, line, start_col, (&x));
    }
    if ((ch == ':')) {
        YStr x = ystr_new(":");
        return Token_new(TokenKind_Colon, line, start_col, (&x));
    }
    if ((ch == ',')) {
        YStr x = ystr_new(",");
        return Token_new(TokenKind_Comma, line, start_col, (&x));
    }
    if ((ch == '=')) {
        YStr x = ystr_new("=");
        return Token_new(TokenKind_Assign, line, start_col, (&x));
    }
    if ((ch == '+')) {
        YStr x = ystr_new("+");
        return Token_new(TokenKind_Plus, line, start_col, (&x));
    }
    if ((ch == '*')) {
        YStr x = ystr_new("*");
        return Token_new(TokenKind_Star, line, start_col, (&x));
    }
    if ((ch == '&')) {
        YStr x = ystr_new("&");
        return Token_new(TokenKind_Ampersand, line, start_col, (&x));
    }
    if ((ch == '<')) {
        YStr x = ystr_new("<");
        return Token_new(TokenKind_Lt, line, start_col, (&x));
    }
    if ((ch == '>')) {
        YStr x = ystr_new(">");
        return Token_new(TokenKind_Gt, line, start_col, (&x));
    }
    bool is_alpha = false;
    if ((ch >= 'a')) {
        if ((ch <= 'z')) {
            is_alpha = true;
        }
    }
    if ((ch >= 'A')) {
        if ((ch <= 'Z')) {
            is_alpha = true;
        }
    }
    if ((ch == '_')) {
        is_alpha = true;
    }
    if (is_alpha) {
        return Lexer_scan_ident_or_keyword(lx, start_col, ch);
    }
    bool is_digit = false;
    if ((ch >= '0')) {
        if ((ch <= '9')) {
            is_digit = true;
        }
    }
    if (is_digit) {
        return Lexer_scan_number(lx, start_col, ch);
    }
    YStr other = ystr_new("?");
    return Token_new(TokenKind_Unknown(ch), line, start_col, (&other));
}

/* impl Lexer */
YVec Lexer_tokenize(Lexer* lx) {
    YVec tokens = yvec_new(32);
    bool parsing = true;
    while (parsing) {
        Token tok = Lexer_next_token(lx);
        size_t len = ystr_len((&tok.lexeme));
        if ((len == 0)) {
            parsing = false;
        } else {
            { __typeof__(tok) __push_tmp = tok; yvec_push((&tokens), &__push_tmp); };
        }
    }
    return tokens;
}

void main(void) {
    printf("%s\n", (ystr_new("--- Y-Lang Self-Hosted Lexer Bootstrapping ---")).data);
    YStr source = ystr_new("fn test() ; let x = 123 }");
    Lexer lexer = Lexer_new((&source));
    bool parsing = true;
    while (parsing) {
        Token tok = Lexer_next_token((&lexer));
        size_t len = ystr_len((&tok.lexeme));
        if ((len == 0)) {
            printf("%s\n", (ystr_new("[EOF]")).data);
            parsing = false;
        } else {
            printf("%s", (ystr_new("Token: ")).data);
            printf("%s\n", (tok.lexeme).data);
        }
    }
    return;
}

