; ================================================
;  Generated by Y-Lang Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---
%Token = type { i32, i32, ptr }
%Lexer = type { ptr }

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare i32 @File_read(...)
declare i32 @SharedMemory_alloc(...)
declare i32 @load(...)
declare i32 @Fragment_zero(...)
declare i32 @Pipeline_init(...)
declare i32 @cp_async(...)
declare i32 @pipe_wait(...)
declare i32 @barrier_sync(...)
declare i32 @ldmatrix(...)
declare i32 @mma_sync(...)
declare i32 @store(...)
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i32)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [4 x i8] c"EOF\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define ptr @load_source(ptr %path.arg) #0 {
entry:
  %path = alloca ptr
  store ptr %path.arg, ptr %path
  %content = alloca i32
  %t1 = load ptr, ptr %path
  %t2 = call i32 @File_read(ptr %t1)
  store i32 %t2, ptr %content
  %t3 = load i32, ptr %content
  %t4 = inttoptr i32 %t3 to ptr
  ret ptr %t4
}

define void @test_structs() #0 {
entry:
  %t = alloca %Token
  %t1 = insertvalue %Token undef, i32 0, 0
  %t2 = insertvalue %Token %t1, i32 42, 1
  %t3 = call ptr @ystr_new(ptr @.str.0)
  %t4 = insertvalue %Token %t2, ptr %t3, 2
  store %Token %t4, ptr %t
  ; lvalue .lexeme
  %t5 = getelementptr %Token, ptr %t, i32 0, i32 2
  %t6 = load ptr, ptr %t5
  %t7 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t6)
  ; lvalue .line
  %t8 = getelementptr %Token, ptr %t, i32 0, i32 1
  %t9 = load i32, ptr %t8
  %t10 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i32 %t9)
  ret void
}

; @kernel target=CPU_AVX512
define void @matmul(ptr %A.arg, ptr %B.arg, ptr %C.arg) #0 {
entry:
  %A = alloca ptr
  store ptr %A.arg, ptr %A
  %B = alloca ptr
  store ptr %B.arg, ptr %B
  %C = alloca ptr
  store ptr %C.arg, ptr %C
  %smem_A = alloca i32
  %weights = alloca half
  %act = alloca half
  %acc = alloca ptr
  %pipe = alloca ptr
  %k = alloca i32
  %tx_A = alloca ptr
  %frag_A = alloca ptr
  %frag_B = alloca ptr
  %frag_C = alloca ptr
  %t1 = call i32 @SharedMemory_alloc()
  store i32 %t1, ptr %smem_A
  %t2 = load ptr, ptr %A
  %t3 = load ptr, ptr %A
  call void @llvm.prefetch.p0(ptr %t3, i32 0, i32 3, i32 1)
  %t4 = load half, ptr %t3
  store half %t4, ptr %weights
  %t5 = load ptr, ptr %B
  %t6 = load ptr, ptr %B
  %t7 = load half, ptr %t6, !nontemporal !0
  store half %t7, ptr %act
  %t8 = call i32 @Fragment_zero()
  %t9 = inttoptr i32 %t8 to ptr
  store ptr %t9, ptr %acc
  %t10 = call i32 @Pipeline_init()
  %t11 = inttoptr i32 %t10 to ptr
  store ptr %t11, ptr %pipe
  store i32 0, ptr %k
  br label %for.cond.1
for.cond.1:
  %t12 = load i32, ptr %k
  %t13 = icmp slt i32 %t12, 1024
  br i1 %t13, label %for.body.2, label %for.end.3
for.body.2:
  %t14 = load ptr, ptr %A
  %t15 = load i32, ptr %k
  %t16 = getelementptr i32, ptr %t14, i64 %t15
  %t17 = load i32, ptr %t16
  %t18 = load i32, ptr %smem_A
  %t19 = call i32 @cp_async(i32 %t17, i32 %t18)
  %t20 = inttoptr i32 %t19 to ptr
  store ptr %t20, ptr %tx_A
  %t21 = load ptr, ptr %tx_A
  %t22 = call i32 @pipe_wait(ptr %t21)
  %t23 = call i32 @barrier_sync()
  %t24 = load i32, ptr %smem_A
  %t25 = call i32 @ldmatrix(i32 %t24)
  %t26 = inttoptr i32 %t25 to ptr
  store ptr %t26, ptr %frag_A
  %t27 = load i32, ptr %smem_A
  %t28 = call i32 @ldmatrix(i32 %t27)
  %t29 = inttoptr i32 %t28 to ptr
  store ptr %t29, ptr %frag_B
  %t30 = load i32, ptr %smem_A
  %t31 = call i32 @ldmatrix(i32 %t30)
  %t32 = inttoptr i32 %t31 to ptr
  store ptr %t32, ptr %frag_C
  ; --- CHISEL INLINE ASM ---
  call void asm sideeffect "ldmatrix.sync.aligned.m8n8.x4.shared.b16 {r0,r1,r2,r3}, [smem_ptr];", "~{memory},~{dirflag},~{fpsr},~{flags}"()
  %t33 = load ptr, ptr %frag_A
  %t34 = load ptr, ptr %frag_B
  %t35 = load ptr, ptr %frag_C
  %t36 = call i32 @mma_sync(ptr %t33, ptr %t34, ptr %t35)
  %t37 = inttoptr i32 %t36 to ptr
  store ptr %t37, ptr %acc
  %t38 = load i32, ptr %k
  %t39 = add i32 %t38, 16
  store i32 %t39, ptr %k
  br label %for.cond.1
for.end.3:
  %t40 = load ptr, ptr %acc
  %t41 = load ptr, ptr %C
  %t42 = call i32 @store(ptr %t40, ptr %t41)
  ret void
}

!0 = !{i32 1}
