; ================================================
;  Generated by Y-Lang Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---
%MyStruct = type { i64, ptr }

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @String_new(...)
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define %MyStruct @MyStruct_new(i64 %a.arg, ptr %b.arg) #0 {
entry:
  %a = alloca i64
  store i64 %a.arg, ptr %a
  %b = alloca ptr
  store ptr %b.arg, ptr %b
  %t1 = load i64, ptr %a
  %t2 = insertvalue %MyStruct undef, i64 %t1, 0
  %t3 = load ptr, ptr %b
  %t4 = insertvalue %MyStruct %t2, ptr %t3, 1
  ret %MyStruct %t4
}

define i32 @main() #0 {
entry:
  %s_str = alloca ptr
  %s = alloca %MyStruct
  %t1 = call ptr @ystr_new(ptr @.str.0)
  %t2 = load ptr, ptr %t1
  %t3 = call ptr @String_new(ptr %t2)
  store ptr %t3, ptr %s_str
  %t4 = load ptr, ptr %s_str
  %t7 = alloca %MyStruct
  call void @MyStruct_new(ptr %t7, i64 42, ptr %s_str)
  %t8 = load %MyStruct, ptr %t7
  %t9 = getelementptr %MyStruct, ptr null, i32 1
  %t10 = ptrtoint ptr %t9 to i64
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %t8, i64 %t10, i1 false)
  ret i32 0
}

!0 = !{i32 1}
