/* ============================================== */
/*  Generated by Y-Lang Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y-Lang Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y-Lang Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y-Lang Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y-Lang Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


typedef struct Span Span;
typedef struct Token Token;
typedef struct FuncDecl FuncDecl;
typedef struct ParamDecl ParamDecl;
typedef struct AstArena AstArena;
typedef struct Parser Parser;

struct Span {
    size_t line;
    size_t col;
};

struct Token {
    TokenKind kind;
    size_t line;
    size_t col;
    YStr lexeme;
};

struct FuncDecl {
    YStr name;
    int32_t is_safe;
    size_t param_count;
    size_t body_start;
    size_t body_count;
    size_t line;
    size_t col;
};

struct ParamDecl {
    YStr name;
    YStr type_str;
};

struct AstArena {
    YVec exprs;
    YVec stmts;
    YVec params;
    YVec funcs;
    YVec arg_indices;
};

struct Parser {
    YVec tokens;
    size_t pos;
    size_t token_count;
};

typedef enum {
    TokenKind_TAG_Kernel,
    TokenKind_TAG_Let,
    TokenKind_TAG_Type,
    TokenKind_TAG_For,
    TokenKind_TAG_In,
    TokenKind_TAG_Step,
    TokenKind_TAG_Return,
    TokenKind_TAG_Const,
    TokenKind_TAG_Pub,
    TokenKind_TAG_Mut,
    TokenKind_TAG_Unsafe,
    TokenKind_TAG_Wait,
    TokenKind_TAG_Emit,
    TokenKind_TAG_Load,
    TokenKind_TAG_Store,
    TokenKind_TAG_Barrier,
    TokenKind_TAG_Struct,
    TokenKind_TAG_Enum,
    TokenKind_TAG_Fn,
    TokenKind_TAG_Match,
    TokenKind_TAG_Safe,
    TokenKind_TAG_Chisel,
    TokenKind_TAG_Import,
    TokenKind_TAG_While,
    TokenKind_TAG_Impl,
    TokenKind_TAG_SelfKw,
    TokenKind_TAG_If,
    TokenKind_TAG_Else,
    TokenKind_TAG_True,
    TokenKind_TAG_False,
    TokenKind_TAG_LBrace,
    TokenKind_TAG_RBrace,
    TokenKind_TAG_LParen,
    TokenKind_TAG_RParen,
    TokenKind_TAG_LBracket,
    TokenKind_TAG_RBracket,
    TokenKind_TAG_Semicolon,
    TokenKind_TAG_Colon,
    TokenKind_TAG_ColonColon,
    TokenKind_TAG_Comma,
    TokenKind_TAG_Dot,
    TokenKind_TAG_DotDot,
    TokenKind_TAG_Arrow,
    TokenKind_TAG_FatArrow,
    TokenKind_TAG_Assign,
    TokenKind_TAG_Plus,
    TokenKind_TAG_Minus,
    TokenKind_TAG_Star,
    TokenKind_TAG_Slash,
    TokenKind_TAG_Percent,
    TokenKind_TAG_Ampersand,
    TokenKind_TAG_AmpAmp,
    TokenKind_TAG_Pipe,
    TokenKind_TAG_PipePipe,
    TokenKind_TAG_Caret,
    TokenKind_TAG_Bang,
    TokenKind_TAG_Lt,
    TokenKind_TAG_Gt,
    TokenKind_TAG_LtEq,
    TokenKind_TAG_GtEq,
    TokenKind_TAG_EqEq,
    TokenKind_TAG_NotEq,
    TokenKind_TAG_LtLt,
    TokenKind_TAG_GtGt,
    TokenKind_TAG_PlusAssign,
    TokenKind_TAG_MinusAssign,
    TokenKind_TAG_StarAssign,
    TokenKind_TAG_SlashAssign,
    TokenKind_TAG_StringTy,
    TokenKind_TAG_VecTy,
    TokenKind_TAG_CharTy,
    TokenKind_TAG_Bool,
    TokenKind_TAG_I32,
    TokenKind_TAG_I64,
    TokenKind_TAG_F32,
    TokenKind_TAG_F64,
    TokenKind_TAG_AtTarget,
    TokenKind_TAG_AtSafe,
    TokenKind_TAG_AtUnsafe,
    TokenKind_TAG_AtCachePolicy,
    TokenKind_TAG_AtStaticAssert,
    TokenKind_TAG_IntLit,
    TokenKind_TAG_FloatLit,
    TokenKind_TAG_StringLit,
    TokenKind_TAG_CharLit,
    TokenKind_TAG_Ident,
    TokenKind_TAG_Eof,
    TokenKind_TAG_Unknown
} TokenKind_Tag;

typedef struct {
    int64_t _0;
} TokenKind_IntLit_Data;

typedef struct {
    int64_t _0;
} TokenKind_FloatLit_Data;

typedef struct {
    YStr _0;
} TokenKind_StringLit_Data;

typedef struct {
    char _0;
} TokenKind_CharLit_Data;

typedef struct {
    YStr _0;
} TokenKind_Ident_Data;

typedef struct {
    char _0;
} TokenKind_Unknown_Data;

typedef struct {
    TokenKind_Tag tag;
    union {
        TokenKind_IntLit_Data IntLit;
        TokenKind_FloatLit_Data FloatLit;
        TokenKind_StringLit_Data StringLit;
        TokenKind_CharLit_Data CharLit;
        TokenKind_Ident_Data Ident;
        TokenKind_Unknown_Data Unknown;
    } data;
} TokenKind;

#define TokenKind_Kernel ((TokenKind){ .tag = TokenKind_TAG_Kernel })
#define TokenKind_Let ((TokenKind){ .tag = TokenKind_TAG_Let })
#define TokenKind_Type ((TokenKind){ .tag = TokenKind_TAG_Type })
#define TokenKind_For ((TokenKind){ .tag = TokenKind_TAG_For })
#define TokenKind_In ((TokenKind){ .tag = TokenKind_TAG_In })
#define TokenKind_Step ((TokenKind){ .tag = TokenKind_TAG_Step })
#define TokenKind_Return ((TokenKind){ .tag = TokenKind_TAG_Return })
#define TokenKind_Const ((TokenKind){ .tag = TokenKind_TAG_Const })
#define TokenKind_Pub ((TokenKind){ .tag = TokenKind_TAG_Pub })
#define TokenKind_Mut ((TokenKind){ .tag = TokenKind_TAG_Mut })
#define TokenKind_Unsafe ((TokenKind){ .tag = TokenKind_TAG_Unsafe })
#define TokenKind_Wait ((TokenKind){ .tag = TokenKind_TAG_Wait })
#define TokenKind_Emit ((TokenKind){ .tag = TokenKind_TAG_Emit })
#define TokenKind_Load ((TokenKind){ .tag = TokenKind_TAG_Load })
#define TokenKind_Store ((TokenKind){ .tag = TokenKind_TAG_Store })
#define TokenKind_Barrier ((TokenKind){ .tag = TokenKind_TAG_Barrier })
#define TokenKind_Struct ((TokenKind){ .tag = TokenKind_TAG_Struct })
#define TokenKind_Enum ((TokenKind){ .tag = TokenKind_TAG_Enum })
#define TokenKind_Fn ((TokenKind){ .tag = TokenKind_TAG_Fn })
#define TokenKind_Match ((TokenKind){ .tag = TokenKind_TAG_Match })
#define TokenKind_Safe ((TokenKind){ .tag = TokenKind_TAG_Safe })
#define TokenKind_Chisel ((TokenKind){ .tag = TokenKind_TAG_Chisel })
#define TokenKind_Import ((TokenKind){ .tag = TokenKind_TAG_Import })
#define TokenKind_While ((TokenKind){ .tag = TokenKind_TAG_While })
#define TokenKind_Impl ((TokenKind){ .tag = TokenKind_TAG_Impl })
#define TokenKind_SelfKw ((TokenKind){ .tag = TokenKind_TAG_SelfKw })
#define TokenKind_If ((TokenKind){ .tag = TokenKind_TAG_If })
#define TokenKind_Else ((TokenKind){ .tag = TokenKind_TAG_Else })
#define TokenKind_True ((TokenKind){ .tag = TokenKind_TAG_True })
#define TokenKind_False ((TokenKind){ .tag = TokenKind_TAG_False })
#define TokenKind_LBrace ((TokenKind){ .tag = TokenKind_TAG_LBrace })
#define TokenKind_RBrace ((TokenKind){ .tag = TokenKind_TAG_RBrace })
#define TokenKind_LParen ((TokenKind){ .tag = TokenKind_TAG_LParen })
#define TokenKind_RParen ((TokenKind){ .tag = TokenKind_TAG_RParen })
#define TokenKind_LBracket ((TokenKind){ .tag = TokenKind_TAG_LBracket })
#define TokenKind_RBracket ((TokenKind){ .tag = TokenKind_TAG_RBracket })
#define TokenKind_Semicolon ((TokenKind){ .tag = TokenKind_TAG_Semicolon })
#define TokenKind_Colon ((TokenKind){ .tag = TokenKind_TAG_Colon })
#define TokenKind_ColonColon ((TokenKind){ .tag = TokenKind_TAG_ColonColon })
#define TokenKind_Comma ((TokenKind){ .tag = TokenKind_TAG_Comma })
#define TokenKind_Dot ((TokenKind){ .tag = TokenKind_TAG_Dot })
#define TokenKind_DotDot ((TokenKind){ .tag = TokenKind_TAG_DotDot })
#define TokenKind_Arrow ((TokenKind){ .tag = TokenKind_TAG_Arrow })
#define TokenKind_FatArrow ((TokenKind){ .tag = TokenKind_TAG_FatArrow })
#define TokenKind_Assign ((TokenKind){ .tag = TokenKind_TAG_Assign })
#define TokenKind_Plus ((TokenKind){ .tag = TokenKind_TAG_Plus })
#define TokenKind_Minus ((TokenKind){ .tag = TokenKind_TAG_Minus })
#define TokenKind_Star ((TokenKind){ .tag = TokenKind_TAG_Star })
#define TokenKind_Slash ((TokenKind){ .tag = TokenKind_TAG_Slash })
#define TokenKind_Percent ((TokenKind){ .tag = TokenKind_TAG_Percent })
#define TokenKind_Ampersand ((TokenKind){ .tag = TokenKind_TAG_Ampersand })
#define TokenKind_AmpAmp ((TokenKind){ .tag = TokenKind_TAG_AmpAmp })
#define TokenKind_Pipe ((TokenKind){ .tag = TokenKind_TAG_Pipe })
#define TokenKind_PipePipe ((TokenKind){ .tag = TokenKind_TAG_PipePipe })
#define TokenKind_Caret ((TokenKind){ .tag = TokenKind_TAG_Caret })
#define TokenKind_Bang ((TokenKind){ .tag = TokenKind_TAG_Bang })
#define TokenKind_Lt ((TokenKind){ .tag = TokenKind_TAG_Lt })
#define TokenKind_Gt ((TokenKind){ .tag = TokenKind_TAG_Gt })
#define TokenKind_LtEq ((TokenKind){ .tag = TokenKind_TAG_LtEq })
#define TokenKind_GtEq ((TokenKind){ .tag = TokenKind_TAG_GtEq })
#define TokenKind_EqEq ((TokenKind){ .tag = TokenKind_TAG_EqEq })
#define TokenKind_NotEq ((TokenKind){ .tag = TokenKind_TAG_NotEq })
#define TokenKind_LtLt ((TokenKind){ .tag = TokenKind_TAG_LtLt })
#define TokenKind_GtGt ((TokenKind){ .tag = TokenKind_TAG_GtGt })
#define TokenKind_PlusAssign ((TokenKind){ .tag = TokenKind_TAG_PlusAssign })
#define TokenKind_MinusAssign ((TokenKind){ .tag = TokenKind_TAG_MinusAssign })
#define TokenKind_StarAssign ((TokenKind){ .tag = TokenKind_TAG_StarAssign })
#define TokenKind_SlashAssign ((TokenKind){ .tag = TokenKind_TAG_SlashAssign })
#define TokenKind_StringTy ((TokenKind){ .tag = TokenKind_TAG_StringTy })
#define TokenKind_VecTy ((TokenKind){ .tag = TokenKind_TAG_VecTy })
#define TokenKind_CharTy ((TokenKind){ .tag = TokenKind_TAG_CharTy })
#define TokenKind_Bool ((TokenKind){ .tag = TokenKind_TAG_Bool })
#define TokenKind_I32 ((TokenKind){ .tag = TokenKind_TAG_I32 })
#define TokenKind_I64 ((TokenKind){ .tag = TokenKind_TAG_I64 })
#define TokenKind_F32 ((TokenKind){ .tag = TokenKind_TAG_F32 })
#define TokenKind_F64 ((TokenKind){ .tag = TokenKind_TAG_F64 })
#define TokenKind_AtTarget ((TokenKind){ .tag = TokenKind_TAG_AtTarget })
#define TokenKind_AtSafe ((TokenKind){ .tag = TokenKind_TAG_AtSafe })
#define TokenKind_AtUnsafe ((TokenKind){ .tag = TokenKind_TAG_AtUnsafe })
#define TokenKind_AtCachePolicy ((TokenKind){ .tag = TokenKind_TAG_AtCachePolicy })
#define TokenKind_AtStaticAssert ((TokenKind){ .tag = TokenKind_TAG_AtStaticAssert })
static inline TokenKind TokenKind_IntLit(int64_t _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_IntLit;
    res.data.IntLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_FloatLit(int64_t _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_FloatLit;
    res.data.FloatLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_StringLit(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_StringLit;
    res.data.StringLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_CharLit(char _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_CharLit;
    res.data.CharLit._0 = _0;
    return res;
}

static inline TokenKind TokenKind_Ident(YStr _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_Ident;
    res.data.Ident._0 = _0;
    return res;
}

#define TokenKind_Eof ((TokenKind){ .tag = TokenKind_TAG_Eof })
static inline TokenKind TokenKind_Unknown(char _0) {
    TokenKind res;
    res.tag = TokenKind_TAG_Unknown;
    res.data.Unknown._0 = _0;
    return res;
}

typedef enum {
    BinaryOp_Add,
    BinaryOp_Sub,
    BinaryOp_Mul,
    BinaryOp_Div,
    BinaryOp_Mod,
    BinaryOp_Eq,
    BinaryOp_NotEq,
    BinaryOp_Lt,
    BinaryOp_Gt,
    BinaryOp_Le,
    BinaryOp_Ge,
    BinaryOp_And,
    BinaryOp_Or,
    BinaryOp_BitAnd,
    BinaryOp_BitOr,
    BinaryOp_BitXor,
    BinaryOp_Shl,
    BinaryOp_Shr
} BinaryOp;

typedef enum {
    UnaryOp_Neg,
    UnaryOp_Not,
    UnaryOp_Ref,
    UnaryOp_Deref
} UnaryOp;

typedef enum {
    Expr_TAG_Ident,
    Expr_TAG_IntLit,
    Expr_TAG_FloatLit,
    Expr_TAG_StringLit,
    Expr_TAG_CharLit,
    Expr_TAG_BoolLit,
    Expr_TAG_SelfLit,
    Expr_TAG_Call,
    Expr_TAG_Index,
    Expr_TAG_MemberAccess,
    Expr_TAG_Path,
    Expr_TAG_BinaryExpr,
    Expr_TAG_UnaryExpr
} Expr_Tag;

typedef struct {
    YStr _0;
} Expr_Ident_Data;

typedef struct {
    int64_t _0;
} Expr_IntLit_Data;

typedef struct {
    int64_t _0;
} Expr_FloatLit_Data;

typedef struct {
    YStr _0;
} Expr_StringLit_Data;

typedef struct {
    char _0;
} Expr_CharLit_Data;

typedef struct {
    int32_t _0;
} Expr_BoolLit_Data;

typedef struct {
    size_t _0;
    size_t _1;
    size_t _2;
} Expr_Call_Data;

typedef struct {
    size_t _0;
    size_t _1;
} Expr_Index_Data;

typedef struct {
    size_t _0;
    YStr _1;
} Expr_MemberAccess_Data;

typedef struct {
    YStr _0;
    YStr _1;
} Expr_Path_Data;

typedef struct {
    size_t _0;
    BinaryOp _1;
    size_t _2;
} Expr_BinaryExpr_Data;

typedef struct {
    UnaryOp _0;
    size_t _1;
} Expr_UnaryExpr_Data;

typedef struct {
    Expr_Tag tag;
    union {
        Expr_Ident_Data Ident;
        Expr_IntLit_Data IntLit;
        Expr_FloatLit_Data FloatLit;
        Expr_StringLit_Data StringLit;
        Expr_CharLit_Data CharLit;
        Expr_BoolLit_Data BoolLit;
        Expr_Call_Data Call;
        Expr_Index_Data Index;
        Expr_MemberAccess_Data MemberAccess;
        Expr_Path_Data Path;
        Expr_BinaryExpr_Data BinaryExpr;
        Expr_UnaryExpr_Data UnaryExpr;
    } data;
} Expr;

static inline Expr Expr_Ident(YStr _0) {
    Expr res;
    res.tag = Expr_TAG_Ident;
    res.data.Ident._0 = _0;
    return res;
}

static inline Expr Expr_IntLit(int64_t _0) {
    Expr res;
    res.tag = Expr_TAG_IntLit;
    res.data.IntLit._0 = _0;
    return res;
}

static inline Expr Expr_FloatLit(int64_t _0) {
    Expr res;
    res.tag = Expr_TAG_FloatLit;
    res.data.FloatLit._0 = _0;
    return res;
}

static inline Expr Expr_StringLit(YStr _0) {
    Expr res;
    res.tag = Expr_TAG_StringLit;
    res.data.StringLit._0 = _0;
    return res;
}

static inline Expr Expr_CharLit(char _0) {
    Expr res;
    res.tag = Expr_TAG_CharLit;
    res.data.CharLit._0 = _0;
    return res;
}

static inline Expr Expr_BoolLit(int32_t _0) {
    Expr res;
    res.tag = Expr_TAG_BoolLit;
    res.data.BoolLit._0 = _0;
    return res;
}

#define Expr_SelfLit ((Expr){ .tag = Expr_TAG_SelfLit })
static inline Expr Expr_Call(size_t _0, size_t _1, size_t _2) {
    Expr res;
    res.tag = Expr_TAG_Call;
    res.data.Call._0 = _0;
    res.data.Call._1 = _1;
    res.data.Call._2 = _2;
    return res;
}

static inline Expr Expr_Index(size_t _0, size_t _1) {
    Expr res;
    res.tag = Expr_TAG_Index;
    res.data.Index._0 = _0;
    res.data.Index._1 = _1;
    return res;
}

static inline Expr Expr_MemberAccess(size_t _0, YStr _1) {
    Expr res;
    res.tag = Expr_TAG_MemberAccess;
    res.data.MemberAccess._0 = _0;
    res.data.MemberAccess._1 = _1;
    return res;
}

static inline Expr Expr_Path(YStr _0, YStr _1) {
    Expr res;
    res.tag = Expr_TAG_Path;
    res.data.Path._0 = _0;
    res.data.Path._1 = _1;
    return res;
}

static inline Expr Expr_BinaryExpr(size_t _0, BinaryOp _1, size_t _2) {
    Expr res;
    res.tag = Expr_TAG_BinaryExpr;
    res.data.BinaryExpr._0 = _0;
    res.data.BinaryExpr._1 = _1;
    res.data.BinaryExpr._2 = _2;
    return res;
}

static inline Expr Expr_UnaryExpr(UnaryOp _0, size_t _1) {
    Expr res;
    res.tag = Expr_TAG_UnaryExpr;
    res.data.UnaryExpr._0 = _0;
    res.data.UnaryExpr._1 = _1;
    return res;
}

typedef enum {
    Stmt_TAG_Let,
    Stmt_TAG_Return,
    Stmt_TAG_If,
    Stmt_TAG_While,
    Stmt_TAG_Assign,
    Stmt_TAG_CompoundAssign,
    Stmt_TAG_ExprStmt
} Stmt_Tag;

typedef struct {
    YStr _0;
    size_t _1;
    size_t _2;
} Stmt_Let_Data;

typedef struct {
    size_t _0;
} Stmt_Return_Data;

typedef struct {
    size_t _0;
    size_t _1;
    size_t _2;
    size_t _3;
    size_t _4;
} Stmt_If_Data;

typedef struct {
    size_t _0;
    size_t _1;
    size_t _2;
} Stmt_While_Data;

typedef struct {
    size_t _0;
    size_t _1;
} Stmt_Assign_Data;

typedef struct {
    size_t _0;
    BinaryOp _1;
    size_t _2;
} Stmt_CompoundAssign_Data;

typedef struct {
    size_t _0;
} Stmt_ExprStmt_Data;

typedef struct {
    Stmt_Tag tag;
    union {
        Stmt_Let_Data Let;
        Stmt_Return_Data Return;
        Stmt_If_Data If;
        Stmt_While_Data While;
        Stmt_Assign_Data Assign;
        Stmt_CompoundAssign_Data CompoundAssign;
        Stmt_ExprStmt_Data ExprStmt;
    } data;
} Stmt;

static inline Stmt Stmt_Let(YStr _0, size_t _1, size_t _2) {
    Stmt res;
    res.tag = Stmt_TAG_Let;
    res.data.Let._0 = _0;
    res.data.Let._1 = _1;
    res.data.Let._2 = _2;
    return res;
}

static inline Stmt Stmt_Return(size_t _0) {
    Stmt res;
    res.tag = Stmt_TAG_Return;
    res.data.Return._0 = _0;
    return res;
}

static inline Stmt Stmt_If(size_t _0, size_t _1, size_t _2, size_t _3, size_t _4) {
    Stmt res;
    res.tag = Stmt_TAG_If;
    res.data.If._0 = _0;
    res.data.If._1 = _1;
    res.data.If._2 = _2;
    res.data.If._3 = _3;
    res.data.If._4 = _4;
    return res;
}

static inline Stmt Stmt_While(size_t _0, size_t _1, size_t _2) {
    Stmt res;
    res.tag = Stmt_TAG_While;
    res.data.While._0 = _0;
    res.data.While._1 = _1;
    res.data.While._2 = _2;
    return res;
}

static inline Stmt Stmt_Assign(size_t _0, size_t _1) {
    Stmt res;
    res.tag = Stmt_TAG_Assign;
    res.data.Assign._0 = _0;
    res.data.Assign._1 = _1;
    return res;
}

static inline Stmt Stmt_CompoundAssign(size_t _0, BinaryOp _1, size_t _2) {
    Stmt res;
    res.tag = Stmt_TAG_CompoundAssign;
    res.data.CompoundAssign._0 = _0;
    res.data.CompoundAssign._1 = _1;
    res.data.CompoundAssign._2 = _2;
    return res;
}

static inline Stmt Stmt_ExprStmt(size_t _0) {
    Stmt res;
    res.tag = Stmt_TAG_ExprStmt;
    res.data.ExprStmt._0 = _0;
    return res;
}

AstArena AstArena_new(void);
Parser Parser_new(YVec tokens, size_t count);
Token Parser_peek(const Parser* p);
Token Parser_advance(Parser* p);
bool Parser_check_eof(const Parser* p);
YStr Parser_match_ident(Parser* p);
void Parser_expect_token(Parser* p, const YStr* expected);
size_t Parser_parse_primary(Parser* p, AstArena* arena);
size_t Parser_parse_postfix(Parser* p, AstArena* arena, size_t lhs_idx);
size_t Parser_get_binop_precedence(const YStr* lex);
BinaryOp Parser_lex_to_binop(const YStr* lex);
size_t Parser_parse_expr_bp(Parser* p, AstArena* arena, size_t min_bp);
size_t Parser_parse_expr(Parser* p, AstArena* arena);
size_t Parser_parse_stmt(Parser* p, AstArena* arena);
size_t Parser_parse_func_decl(Parser* p, AstArena* arena, int32_t is_safe);
bool Parser_parse_item(Parser* p, AstArena* arena);
void Parser_parse_program(Parser* p, AstArena* arena);
void main(void);

/* impl AstArena */
AstArena AstArena_new(void) {
    AstArena arena;
    arena.exprs = yvec_new(64);
    arena.stmts = yvec_new(64);
    arena.params = yvec_new(32);
    arena.funcs = yvec_new(32);
    arena.arg_indices = yvec_new(8);
    return arena;
}

/* impl Parser */
Parser Parser_new(YVec tokens, size_t count) {
    Parser p;
    p.tokens = tokens;
    p.pos = 0;
    p.token_count = count;
    return p;
}

Token Parser_peek(const Parser* p) {
    if (((*p).pos < (*p).token_count)) {
        Token tok;
        tok.kind = TokenKind_Eof;
        tok.line = 0;
        tok.col = 0;
        tok.lexeme = ystr_new("");
        return tok;
    }
    Token eof;
    eof.kind = TokenKind_Eof;
    eof.line = 0;
    eof.col = 0;
    eof.lexeme = ystr_new("");
    return eof;
}

Token Parser_advance(Parser* p) {
    Token tok = Parser_peek(p);
    if (((*p).pos < (*p).token_count)) {
        (*p).pos += 1;
    }
    return tok;
}

bool Parser_check_eof(const Parser* p) {
    if (((*p).pos >= (*p).token_count)) {
        return true;
    }
    return false;
}

YStr Parser_match_ident(Parser* p) {
    Token tok = Parser_peek(p);
    YStr lex = ystr_clone((&tok.lexeme));
    size_t len = ystr_len((&lex));
    if ((len > 0)) {
        char ch = ystr_char_at((&lex), 0);
        bool is_ident = false;
        if ((ch >= 'a')) {
            if ((ch <= 'z')) {
                is_ident = true;
            }
        }
        if ((ch >= 'A')) {
            if ((ch <= 'Z')) {
                is_ident = true;
            }
        }
        if ((ch == '_')) {
            is_ident = true;
        }
        if (is_ident) {
            Parser_advance(p);
            return lex;
        }
    }
    return ystr_new("");
}

void Parser_expect_token(Parser* p, const YStr* expected) {
    Token tok = Parser_advance(p);
    bool matches = ystr_eq((&tok.lexeme), expected);
    if (matches) {
        return;
    }
    printf("%s", (ystr_new("Syntax Error: Expected '")).data);
    printf("%s", (expected)->data);
    printf("%s", (ystr_new("' but found '")).data);
    printf("%s", (tok.lexeme).data);
    printf("%s", (ystr_new("' at line ")).data);
    printf("%d\n", (int)tok.line);
    printf("%s\n", (ystr_new("")).data);
    return;
}

/* impl Parser */
size_t Parser_parse_primary(Parser* p, AstArena* arena) {
    Token tok = Parser_peek(p);
    YStr lex = ystr_clone((&tok.lexeme));
    size_t line = tok.line;
    size_t col = tok.col;
    size_t len = ystr_len((&lex));
    if ((len > 0)) {
        char ch = ystr_char_at((&lex), 0);
        bool is_digit = false;
        if ((ch >= '0')) {
            if ((ch <= '9')) {
                is_digit = true;
            }
        }
        if (is_digit) {
            Parser_advance(p);
            Expr expr = Expr_IntLit(0);
            { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            size_t idx = yvec_len((&(*arena).exprs));
            return idx;
        }
        if ((ch == '"')) {
            Parser_advance(p);
            Expr expr = Expr_StringLit(ystr_clone((&lex)));
            { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            size_t idx = yvec_len((&(*arena).exprs));
            return idx;
        }
        if (ystr_eq_cstr((&lex), "true")) {
            Parser_advance(p);
            Expr expr = Expr_BoolLit(1);
            { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            size_t idx = yvec_len((&(*arena).exprs));
            return idx;
        }
        if (ystr_eq_cstr((&lex), "false")) {
            Parser_advance(p);
            Expr expr = Expr_BoolLit(0);
            { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            size_t idx = yvec_len((&(*arena).exprs));
            return idx;
        }
        bool is_ident = false;
        if ((ch >= 'a')) {
            if ((ch <= 'z')) {
                is_ident = true;
            }
        }
        if ((ch >= 'A')) {
            if ((ch <= 'Z')) {
                is_ident = true;
            }
        }
        if ((ch == '_')) {
            is_ident = true;
        }
        if (is_ident) {
            Parser_advance(p);
            Token next = Parser_peek(p);
            if (ystr_eq_cstr((&next.lexeme), "::")) {
                Parser_advance(p);
                Token member_tok = Parser_advance(p);
                YStr member_lex = ystr_clone((&member_tok.lexeme));
                Expr expr = Expr_Path(ystr_clone((&lex)), member_lex);
                { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
                size_t idx = yvec_len((&(*arena).exprs));
                return idx;
            }
            Expr expr = Expr_Ident(ystr_clone((&lex)));
            { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            size_t idx = yvec_len((&(*arena).exprs));
            return idx;
        }
    }
    if (ystr_eq_cstr((&lex), "(")) {
        Parser_advance(p);
        size_t inner_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(")"); &__tmp; }));
        return inner_idx;
    }
    if (ystr_eq_cstr((&lex), "&")) {
        Parser_advance(p);
        size_t operand_idx = Parser_parse_primary(p, arena);
        Expr expr = Expr_UnaryExpr(UnaryOp_Ref, operand_idx);
        { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).exprs));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "*")) {
        Parser_advance(p);
        size_t operand_idx = Parser_parse_primary(p, arena);
        Expr expr = Expr_UnaryExpr(UnaryOp_Deref, operand_idx);
        { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).exprs));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "-")) {
        Parser_advance(p);
        size_t operand_idx = Parser_parse_primary(p, arena);
        Expr expr = Expr_UnaryExpr(UnaryOp_Neg, operand_idx);
        { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).exprs));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "!")) {
        Parser_advance(p);
        size_t operand_idx = Parser_parse_primary(p, arena);
        Expr expr = Expr_UnaryExpr(UnaryOp_Not, operand_idx);
        { __typeof__(expr) __push_tmp = expr; yvec_push((&(*arena).exprs), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).exprs));
        return idx;
    }
    printf("%s", (ystr_new("[!] Parse error: unexpected token '")).data);
    printf("%s", (lex).data);
    printf("%s", (ystr_new("' at line ")).data);
    printf("%d\n", (int)tok.line);
    printf("%s\n", (ystr_new("")).data);
    Expr dummy = Expr_IntLit(0);
    { __typeof__(dummy) __push_tmp = dummy; yvec_push((&(*arena).exprs), &__push_tmp); };
    size_t idx = yvec_len((&(*arena).exprs));
    return idx;
}

size_t Parser_parse_postfix(Parser* p, AstArena* arena, size_t lhs_idx) {
    size_t current = lhs_idx;
    bool running = true;
    while (running) {
        Token tok = Parser_peek(p);
        YStr lex = ystr_clone((&tok.lexeme));
        if (ystr_eq_cstr((&lex), "(")) {
            Parser_advance(p);
            size_t args_start = yvec_len((&(*arena).arg_indices));
            size_t arg_count = 0;
            bool parsing_args = true;
            while (parsing_args) {
                Token check = Parser_peek(p);
                if (ystr_eq_cstr((&check.lexeme), ")")) {
                    parsing_args = false;
                } else {
                    size_t arg_idx = Parser_parse_expr(p, arena);
                    { __typeof__(arg_idx) __push_tmp = arg_idx; yvec_push((&(*arena).arg_indices), &__push_tmp); };
                    arg_count += 1;
                    Token comma_check = Parser_peek(p);
                    if (ystr_eq_cstr((&comma_check.lexeme), ",")) {
                        Parser_advance(p);
                    } else {
                        parsing_args = false;
                    }
                }
            }
            Parser_expect_token(p, ({ YStr __tmp = ystr_new(")"); &__tmp; }));
            Expr call_expr = Expr_Call(current, args_start, arg_count);
            { __typeof__(call_expr) __push_tmp = call_expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            current = yvec_len((&(*arena).exprs));
        } else         if (ystr_eq_cstr((&lex), ".")) {
            Parser_advance(p);
            Token member_tok = Parser_advance(p);
            YStr member_name = ystr_clone((&member_tok.lexeme));
            Expr acc_expr = Expr_MemberAccess(current, member_name);
            { __typeof__(acc_expr) __push_tmp = acc_expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            current = yvec_len((&(*arena).exprs));
        } else         if (ystr_eq_cstr((&lex), "[")) {
            Parser_advance(p);
            size_t index_idx = Parser_parse_expr(p, arena);
            Parser_expect_token(p, ({ YStr __tmp = ystr_new("]"); &__tmp; }));
            Expr idx_expr = Expr_Index(current, index_idx);
            { __typeof__(idx_expr) __push_tmp = idx_expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            current = yvec_len((&(*arena).exprs));
        } else {
            running = false;
        }
    }
    return current;
}

size_t Parser_get_binop_precedence(const YStr* lex) {
    if (ystr_eq_cstr(lex, "||")) {
        return 1;
    }
    if (ystr_eq_cstr(lex, "&&")) {
        return 3;
    }
    if (ystr_eq_cstr(lex, "==")) {
        return 5;
    }
    if (ystr_eq_cstr(lex, "!=")) {
        return 5;
    }
    if (ystr_eq_cstr(lex, "<")) {
        return 7;
    }
    if (ystr_eq_cstr(lex, ">")) {
        return 7;
    }
    if (ystr_eq_cstr(lex, "<=")) {
        return 7;
    }
    if (ystr_eq_cstr(lex, ">=")) {
        return 7;
    }
    if (ystr_eq_cstr(lex, "|")) {
        return 9;
    }
    if (ystr_eq_cstr(lex, "^")) {
        return 9;
    }
    if (ystr_eq_cstr(lex, "&")) {
        return 11;
    }
    if (ystr_eq_cstr(lex, "+")) {
        return 15;
    }
    if (ystr_eq_cstr(lex, "-")) {
        return 15;
    }
    if (ystr_eq_cstr(lex, "*")) {
        return 17;
    }
    if (ystr_eq_cstr(lex, "/")) {
        return 17;
    }
    if (ystr_eq_cstr(lex, "%")) {
        return 17;
    }
    return 0;
}

BinaryOp Parser_lex_to_binop(const YStr* lex) {
    if (ystr_eq_cstr(lex, "+")) {
        return BinaryOp_Add;
    }
    if (ystr_eq_cstr(lex, "-")) {
        return BinaryOp_Sub;
    }
    if (ystr_eq_cstr(lex, "*")) {
        return BinaryOp_Mul;
    }
    if (ystr_eq_cstr(lex, "/")) {
        return BinaryOp_Div;
    }
    if (ystr_eq_cstr(lex, "%")) {
        return BinaryOp_Mod;
    }
    if (ystr_eq_cstr(lex, "==")) {
        return BinaryOp_Eq;
    }
    if (ystr_eq_cstr(lex, "!=")) {
        return BinaryOp_NotEq;
    }
    if (ystr_eq_cstr(lex, "<")) {
        return BinaryOp_Lt;
    }
    if (ystr_eq_cstr(lex, ">")) {
        return BinaryOp_Gt;
    }
    if (ystr_eq_cstr(lex, "<=")) {
        return BinaryOp_Le;
    }
    if (ystr_eq_cstr(lex, ">=")) {
        return BinaryOp_Ge;
    }
    if (ystr_eq_cstr(lex, "&&")) {
        return BinaryOp_And;
    }
    if (ystr_eq_cstr(lex, "||")) {
        return BinaryOp_Or;
    }
    if (ystr_eq_cstr(lex, "&")) {
        return BinaryOp_BitAnd;
    }
    if (ystr_eq_cstr(lex, "|")) {
        return BinaryOp_BitOr;
    }
    if (ystr_eq_cstr(lex, "^")) {
        return BinaryOp_BitXor;
    }
    return BinaryOp_Add;
}

size_t Parser_parse_expr_bp(Parser* p, AstArena* arena, size_t min_bp) {
    size_t lhs = Parser_parse_primary(p, arena);
    lhs = Parser_parse_postfix(p, arena, lhs);
    bool looping = true;
    while (looping) {
        Token tok = Parser_peek(p);
        YStr lex = ystr_clone((&tok.lexeme));
        size_t prec = Parser_get_binop_precedence((&lex));
        if ((prec == 0)) {
            looping = false;
        } else         if ((prec < min_bp)) {
            looping = false;
        } else {
            Parser_advance(p);
            BinaryOp op = Parser_lex_to_binop((&lex));
            size_t rhs = Parser_parse_expr_bp(p, arena, (prec + 1));
            Expr bin_expr = Expr_BinaryExpr(lhs, op, rhs);
            { __typeof__(bin_expr) __push_tmp = bin_expr; yvec_push((&(*arena).exprs), &__push_tmp); };
            lhs = yvec_len((&(*arena).exprs));
            lhs = Parser_parse_postfix(p, arena, lhs);
        }
    }
    return lhs;
}

size_t Parser_parse_expr(Parser* p, AstArena* arena) {
    return Parser_parse_expr_bp(p, arena, 0);
}

/* impl Parser */
size_t Parser_parse_stmt(Parser* p, AstArena* arena) {
    Token tok = Parser_peek(p);
    YStr lex = ystr_clone((&tok.lexeme));
    if (ystr_eq_cstr((&lex), "let")) {
        Parser_advance(p);
        Token mut_check = Parser_peek(p);
        if (ystr_eq_cstr((&mut_check.lexeme), "mut")) {
            Parser_advance(p);
        }
        Token name_tok = Parser_advance(p);
        YStr var_name = ystr_clone((&name_tok.lexeme));
        size_t type_idx = 0;
        Token colon_check = Parser_peek(p);
        if (ystr_eq_cstr((&colon_check.lexeme), ":")) {
            Parser_advance(p);
            bool skipping_type = true;
            while (skipping_type) {
                Token t = Parser_peek(p);
                if (ystr_eq_cstr((&t.lexeme), "=")) {
                    skipping_type = false;
                } else                 if (ystr_eq_cstr((&t.lexeme), ";")) {
                    skipping_type = false;
                } else {
                    Parser_advance(p);
                }
            }
        }
        size_t init_idx = 0;
        Token eq_check = Parser_peek(p);
        if (ystr_eq_cstr((&eq_check.lexeme), "=")) {
            Parser_advance(p);
            init_idx = Parser_parse_expr(p, arena);
        }
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
        Stmt stmt = Stmt_Let(var_name, type_idx, init_idx);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "return")) {
        Parser_advance(p);
        size_t ret_idx = 0;
        Token semi_check = Parser_peek(p);
        if (ystr_eq_cstr((&semi_check.lexeme), ";")) {
        } else {
            ret_idx = Parser_parse_expr(p, arena);
        }
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
        Stmt stmt = Stmt_Return(ret_idx);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "if")) {
        Parser_advance(p);
        size_t cond_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
        size_t then_start = yvec_len((&(*arena).stmts));
        size_t then_count = 0;
        bool parsing_then = true;
        while (parsing_then) {
            Token check = Parser_peek(p);
            if (ystr_eq_cstr((&check.lexeme), "}")) {
                parsing_then = false;
            } else {
                Parser_parse_stmt(p, arena);
                then_count += 1;
            }
        }
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("}"); &__tmp; }));
        size_t else_start = 0;
        size_t else_count = 0;
        Token else_check = Parser_peek(p);
        if (ystr_eq_cstr((&else_check.lexeme), "else")) {
            Parser_advance(p);
            Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
            else_start = yvec_len((&(*arena).stmts));
            bool parsing_else = true;
            while (parsing_else) {
                Token check2 = Parser_peek(p);
                if (ystr_eq_cstr((&check2.lexeme), "}")) {
                    parsing_else = false;
                } else {
                    Parser_parse_stmt(p, arena);
                    else_count += 1;
                }
            }
            Parser_expect_token(p, ({ YStr __tmp = ystr_new("}"); &__tmp; }));
        }
        Stmt stmt = Stmt_If(cond_idx, then_start, then_count, else_start, else_count);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    if (ystr_eq_cstr((&lex), "while")) {
        Parser_advance(p);
        size_t cond_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
        size_t body_start = yvec_len((&(*arena).stmts));
        size_t body_count = 0;
        bool parsing_body = true;
        while (parsing_body) {
            Token check = Parser_peek(p);
            if (ystr_eq_cstr((&check.lexeme), "}")) {
                parsing_body = false;
            } else {
                Parser_parse_stmt(p, arena);
                body_count += 1;
            }
        }
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("}"); &__tmp; }));
        Stmt stmt = Stmt_While(cond_idx, body_start, body_count);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    size_t expr_idx = Parser_parse_expr(p, arena);
    Token assign_check = Parser_peek(p);
    if (ystr_eq_cstr((&assign_check.lexeme), "=")) {
        Parser_advance(p);
        size_t value_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
        Stmt stmt = Stmt_Assign(expr_idx, value_idx);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    if (ystr_eq_cstr((&assign_check.lexeme), "+=")) {
        Parser_advance(p);
        size_t val_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
        Stmt stmt = Stmt_CompoundAssign(expr_idx, BinaryOp_Add, val_idx);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    if (ystr_eq_cstr((&assign_check.lexeme), "-=")) {
        Parser_advance(p);
        size_t val_idx = Parser_parse_expr(p, arena);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
        Stmt stmt = Stmt_CompoundAssign(expr_idx, BinaryOp_Sub, val_idx);
        { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
        size_t idx = yvec_len((&(*arena).stmts));
        return idx;
    }
    Parser_expect_token(p, ({ YStr __tmp = ystr_new(";"); &__tmp; }));
    Stmt stmt = Stmt_ExprStmt(expr_idx);
    { __typeof__(stmt) __push_tmp = stmt; yvec_push((&(*arena).stmts), &__push_tmp); };
    size_t idx = yvec_len((&(*arena).stmts));
    return idx;
}

/* impl Parser */
size_t Parser_parse_func_decl(Parser* p, AstArena* arena, int32_t is_safe) {
    Token name_tok = Parser_advance(p);
    YStr fn_name = ystr_clone((&name_tok.lexeme));
    size_t line = name_tok.line;
    size_t col = name_tok.col;
    Parser_expect_token(p, ({ YStr __tmp = ystr_new("("); &__tmp; }));
    size_t param_count = 0;
    bool parsing_params = true;
    while (parsing_params) {
        Token check = Parser_peek(p);
        if (ystr_eq_cstr((&check.lexeme), ")")) {
            parsing_params = false;
        } else {
            Token pname_tok = Parser_advance(p);
            YStr pname = ystr_clone((&pname_tok.lexeme));
            Parser_expect_token(p, ({ YStr __tmp = ystr_new(":"); &__tmp; }));
            YStr type_str = ystr_new("");
            bool skipping = true;
            while (skipping) {
                Token t = Parser_peek(p);
                if (ystr_eq_cstr((&t.lexeme), ",")) {
                    skipping = false;
                } else                 if (ystr_eq_cstr((&t.lexeme), ")")) {
                    skipping = false;
                } else {
                    YStr tlex = ystr_clone((&t.lexeme));
                    ystr_push((&type_str), ' ');
                    Parser_advance(p);
                }
            }
            ParamDecl param;
            param.name = pname;
            param.type_str = type_str;
            { __typeof__(param) __push_tmp = param; yvec_push((&(*arena).params), &__push_tmp); };
            param_count += 1;
            Token comma_check = Parser_peek(p);
            if (ystr_eq_cstr((&comma_check.lexeme), ",")) {
                Parser_advance(p);
            }
        }
    }
    Parser_expect_token(p, ({ YStr __tmp = ystr_new(")"); &__tmp; }));
    Token arrow_check = Parser_peek(p);
    if (ystr_eq_cstr((&arrow_check.lexeme), "->")) {
        Parser_advance(p);
        bool skip_ret = true;
        while (skip_ret) {
            Token t = Parser_peek(p);
            if (ystr_eq_cstr((&t.lexeme), "{")) {
                skip_ret = false;
            } else {
                Parser_advance(p);
            }
        }
    }
    Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
    size_t body_start = yvec_len((&(*arena).stmts));
    size_t body_count = 0;
    bool parsing_body = true;
    while (parsing_body) {
        Token check = Parser_peek(p);
        if (ystr_eq_cstr((&check.lexeme), "}")) {
            parsing_body = false;
        } else {
            Parser_parse_stmt(p, arena);
            body_count += 1;
        }
    }
    Parser_expect_token(p, ({ YStr __tmp = ystr_new("}"); &__tmp; }));
    FuncDecl fdecl;
    fdecl.name = fn_name;
    fdecl.is_safe = is_safe;
    fdecl.param_count = param_count;
    fdecl.body_start = body_start;
    fdecl.body_count = body_count;
    fdecl.line = line;
    fdecl.col = col;
    { __typeof__(fdecl) __push_tmp = fdecl; yvec_push((&(*arena).funcs), &__push_tmp); };
    size_t idx = yvec_len((&(*arena).funcs));
    return idx;
}

/* impl Parser */
bool Parser_parse_item(Parser* p, AstArena* arena) {
    Token tok = Parser_peek(p);
    YStr lex = ystr_clone((&tok.lexeme));
    if (ystr_eq_cstr((&lex), "fn")) {
        Parser_advance(p);
        Parser_parse_func_decl(p, arena, 1);
        return true;
    }
    if (ystr_eq_cstr((&lex), "@safe")) {
        Parser_advance(p);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("fn"); &__tmp; }));
        Parser_parse_func_decl(p, arena, 1);
        return true;
    }
    if (ystr_eq_cstr((&lex), "@unsafe")) {
        Parser_advance(p);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("fn"); &__tmp; }));
        Parser_parse_func_decl(p, arena, 0);
        return true;
    }
    if (ystr_eq_cstr((&lex), "struct")) {
        Parser_advance(p);
        Token _name = Parser_advance(p);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
        size_t depth = 1;
        while ((depth > 0)) {
            Token t = Parser_advance(p);
            if (ystr_eq_cstr((&t.lexeme), "{")) {
                depth += 1;
            }
            if (ystr_eq_cstr((&t.lexeme), "}")) {
                depth -= 1;
            }
        }
        return true;
    }
    if (ystr_eq_cstr((&lex), "enum")) {
        Parser_advance(p);
        Token _name = Parser_advance(p);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
        size_t depth = 1;
        while ((depth > 0)) {
            Token t = Parser_advance(p);
            if (ystr_eq_cstr((&t.lexeme), "{")) {
                depth += 1;
            }
            if (ystr_eq_cstr((&t.lexeme), "}")) {
                depth -= 1;
            }
        }
        return true;
    }
    if (ystr_eq_cstr((&lex), "impl")) {
        Parser_advance(p);
        Token _type_name = Parser_advance(p);
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("{"); &__tmp; }));
        bool parsing_impl = true;
        while (parsing_impl) {
            Token check = Parser_peek(p);
            if (ystr_eq_cstr((&check.lexeme), "}")) {
                parsing_impl = false;
            } else {
                int32_t method_safe = 1;
                if (ystr_eq_cstr((&check.lexeme), "@unsafe")) {
                    Parser_advance(p);
                    method_safe = 0;
                } else                 if (ystr_eq_cstr((&check.lexeme), "@safe")) {
                    Parser_advance(p);
                }
                Token pub_check = Parser_peek(p);
                if (ystr_eq_cstr((&pub_check.lexeme), "pub")) {
                    Parser_advance(p);
                }
                Parser_expect_token(p, ({ YStr __tmp = ystr_new("fn"); &__tmp; }));
                Parser_parse_func_decl(p, arena, method_safe);
            }
        }
        Parser_expect_token(p, ({ YStr __tmp = ystr_new("}"); &__tmp; }));
        return true;
    }
    if (ystr_eq_cstr((&lex), "import")) {
        Parser_advance(p);
        bool skip_import = true;
        while (skip_import) {
            Token t = Parser_advance(p);
            if (ystr_eq_cstr((&t.lexeme), ";")) {
                skip_import = false;
            }
        }
        return true;
    }
    if (ystr_eq_cstr((&lex), "")) {
        return false;
    }
    printf("%s", (ystr_new("[!] Skipping unknown top-level token: '")).data);
    printf("%s", (lex).data);
    printf("%s\n", (ystr_new("'")).data);
    Parser_advance(p);
    return true;
}

void Parser_parse_program(Parser* p, AstArena* arena) {
    bool parsing = true;
    while (parsing) {
        bool has_more = Parser_parse_item(p, arena);
        if (has_more) {
        } else {
            parsing = false;
        }
    }
}

void main(void) {
    printf("%s\n", (ystr_new("--- Y-Lang Self-Hosted Parser (DOD Arena) ---")).data);
    AstArena arena = AstArena_new();
    printf("%s\n", (ystr_new("Arena initialized.")).data);
    printf("%s\n", (ystr_new("Expr arena ready.")).data);
    printf("%s\n", (ystr_new("Stmt arena ready.")).data);
    printf("%s\n", (ystr_new("Func arena ready.")).data);
    printf("%s\n", (ystr_new("--- Parser module compiled successfully ---")).data);
    return;
}

