// ============================================================
//  Y-Lang  —  Parser Engine
//  parser.rs
//
//  Parses the token stream generated by lexer.rs into the 
//  hierarchical AST defined in ast.rs.
// ============================================================

#![allow(dead_code)]

use crate::lexer::{Token, TokenKind};
use crate::ast::*;

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    fn peek(&self) -> &Token {
        if self.pos < self.tokens.len() {
            &self.tokens[self.pos]
        } else {
            &self.tokens[self.tokens.len() - 1] // EOF
        }
    }

    fn advance(&mut self) -> Token {
        let tok = self.peek().clone();
        if self.pos < self.tokens.len() - 1 {
            self.pos += 1;
        }
        tok
    }

    fn check(&self, kind: TokenKind) -> bool {
        self.peek().kind == kind
    }

    fn match_token(&mut self, kind: TokenKind) -> bool {
        if self.check(kind.clone()) {
            self.advance();
            true
        } else {
            false
        }
    }

    fn expect(&mut self, kind: TokenKind, msg: &str) -> Result<Token, String> {
        let tok = self.peek().clone();
        if std::mem::discriminant(&tok.kind) == std::mem::discriminant(&kind) || tok.kind == kind {
            Ok(self.advance())
        } else {
            Err(format!("Line {}: Expected {} but found {:?}", tok.line, msg, tok.kind))
        }
    }

    // ── Entry Point ─────────────────────────────────────────

    pub fn parse_program(&mut self) -> Result<Program, String> {
        let mut items = Vec::new();

        while !self.check(TokenKind::Eof) {
            items.push(self.parse_item()?);
        }

        Ok(Program { items })
    }

    fn parse_item(&mut self) -> Result<Item, String> {
        // Handle import declarations
        if self.match_token(TokenKind::Import) {
            let imp = self.parse_import()?;
            return Ok(Item::Import(imp));
        }

        // Handle @static_assert
        if self.match_token(TokenKind::AtStaticAssert) {
            let sa = self.parse_static_assert()?;
            return Ok(Item::StaticAssert(sa));
        }

        // Look for @target attribute
        let mut target = None;
        if self.match_token(TokenKind::AtTarget) {
            self.expect(TokenKind::LParen, "'(' after @target")?;
            let tok = self.peek().clone();
            if let TokenKind::HardwareTarget(name) = &tok.kind {
                target = Some(HardwareTarget {
                    name: name.clone(),
                    span: Span { line: tok.line, col: tok.col },
                });
                self.advance();
            } else {
                return Err(format!("Line {}: Expected hardware target profile", tok.line));
            }
            self.expect(TokenKind::RParen, "')' after hardware target")?;
        }

        if self.match_token(TokenKind::Kernel) {
            let kernel = self.parse_kernel(target)?;
            Ok(Item::Kernel(kernel))
        } else if self.match_token(TokenKind::Struct) {
            let s = self.parse_struct_decl()?;
            Ok(Item::Struct(s))
        } else if self.match_token(TokenKind::Enum) {
            let e = self.parse_enum_decl()?;
            Ok(Item::Enum(e))
        } else if self.match_token(TokenKind::Fn) {
            let f = self.parse_func_decl(true)?;
            Ok(Item::Func(f))
        } else if self.match_token(TokenKind::AtSafe) {
            self.expect(TokenKind::Fn, "'fn' after safe")?;
            let f = self.parse_func_decl(true)?;
            Ok(Item::Func(f))
        } else if self.match_token(TokenKind::AtUnsafe) {
            self.expect(TokenKind::Fn, "'fn' after unsafe")?;
            let f = self.parse_func_decl(false)?;
            Ok(Item::Func(f))
        } else if self.match_token(TokenKind::Impl) {
            let imp = self.parse_impl_block()?;
            Ok(Item::Impl(imp))
        } else {
            let tok = self.peek();
            Err(format!("Line {}: Error: Unexpected top-level item.", tok.line))
        }
    }

    // ── Declarations ──────────────────────────────────────────────
    
    fn parse_struct_decl(&mut self) -> Result<StructDecl, String> {
        let name_tok = self.peek().clone();
        let name = match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); s.clone() },
            _ => return Err("Expected struct name".into())
        };
        let span = Span { line: name_tok.line, col: name_tok.col };

        // Parse optional generic parameters: <T, SIZE>
        let mut generic_params = Vec::new();
        if self.match_token(TokenKind::Lt) {
            while !self.check(TokenKind::Gt) && !self.check(TokenKind::Eof) {
                let p_tok = self.peek().clone();
                let p_name = match &p_tok.kind {
                    TokenKind::Ident(s) => { self.advance(); s.clone() },
                    _ => return Err(format!("Line {}: Expected generic parameter name", p_tok.line)),
                };
                generic_params.push(GenericParam {
                    name: p_name,
                    span: Span { line: p_tok.line, col: p_tok.col },
                });
                if !self.match_token(TokenKind::Comma) { break; }
            }
            self.expect(TokenKind::Gt, "'>' to close generic parameters")?;
        }

        self.expect(TokenKind::LBrace, "'{' to begin struct body")?;
        let mut fields = Vec::new();
        while !self.check(TokenKind::RBrace) && !self.check(TokenKind::Eof) {
            // Parse field attributes: @gpu_uncached, @atomic, @align(...)
            let mut attrs = Vec::new();
            loop {
                let attr_tok = self.peek().clone();
                let attr_span = Span { line: attr_tok.line, col: attr_tok.col };
                if self.match_token(TokenKind::AtGpuUncached) {
                    attrs.push(FieldAttr { kind: FieldAttrKind::GpuUncached, span: attr_span });
                } else if self.match_token(TokenKind::AtAtomic) {
                    attrs.push(FieldAttr { kind: FieldAttrKind::Atomic, span: attr_span });
                } else if self.match_token(TokenKind::AtAlign) {
                    self.expect(TokenKind::LParen, "'(' after @align")?;
                    let align_expr = self.parse_primary_expr()?;
                    self.expect(TokenKind::RParen, "')' after @align value")?;
                    attrs.push(FieldAttr { kind: FieldAttrKind::Align(align_expr), span: attr_span });
                } else {
                    break;
                }
            }

            let f_name_tok = self.peek().clone();
            let f_name = match &f_name_tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                _ => break,
            };
            self.expect(TokenKind::Colon, "':' after field name")?;
            let ty = self.parse_type()?;
            fields.push(Field { attrs, name: f_name, ty });
            if !self.match_token(TokenKind::Comma) && !self.check(TokenKind::RBrace) {
                 break;
            }
        }
        self.expect(TokenKind::RBrace, "'}' to end struct body")?;
        Ok(StructDecl { name, generic_params, fields, span })
    }

    fn parse_enum_decl(&mut self) -> Result<EnumDecl, String> {
        let name_tok = self.peek().clone();
        let name = match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); s.clone() },
            _ => return Err("Expected enum name".into())
        };
        let span = Span { line: name_tok.line, col: name_tok.col };

        // Optional generic params: enum Option<T> { ... }
        let mut generic_params = Vec::new();
        if self.match_token(TokenKind::Lt) {
            while !self.check(TokenKind::Gt) && !self.check(TokenKind::Eof) {
                let p_tok = self.peek().clone();
                let p_name = match &p_tok.kind {
                    TokenKind::Ident(s) => { self.advance(); s.clone() },
                    _ => return Err(format!("Line {}: Expected generic parameter name", p_tok.line)),
                };
                generic_params.push(GenericParam {
                    name: p_name,
                    span: Span { line: p_tok.line, col: p_tok.col },
                });
                if !self.match_token(TokenKind::Comma) { break; }
            }
            self.expect(TokenKind::Gt, "'>' to close generic parameters")?;
        }

        self.expect(TokenKind::LBrace, "'{' to begin enum body")?;
        let mut variants = Vec::new();
        while !self.check(TokenKind::RBrace) && !self.check(TokenKind::Eof) {
            let v_tok = self.peek().clone();
            let v_span = Span { line: v_tok.line, col: v_tok.col };
            // Accept both Ident tokens and keyword tokens as variant names
            let v_name = self.parse_any_ident()?;
            // Check for tuple variant: Variant(Type, Type)
            let fields = if self.match_token(TokenKind::LParen) {
                let mut types = Vec::new();
                while !self.check(TokenKind::RParen) && !self.check(TokenKind::Eof) {
                    types.push(self.parse_type()?);
                    if !self.match_token(TokenKind::Comma) { break; }
                }
                self.expect(TokenKind::RParen, "')' after enum variant fields")?;
                Some(types)
            } else {
                None
            };
            variants.push(EnumVariant { name: v_name, fields, span: v_span });
            self.match_token(TokenKind::Comma);
        }
        self.expect(TokenKind::RBrace, "'}' to end enum body")?;
        Ok(EnumDecl { name, generic_params, variants, span })
    }

    /// Parse any identifier, including keywords used as names (e.g., enum variant `Kernel`)
    fn parse_any_ident(&mut self) -> Result<String, String> {
        let tok = self.peek().clone();
        let name = match &tok.kind {
            TokenKind::Ident(s) => s.clone(),
            _ => {
                let s = &tok.lexeme;
                if let Some(c) = s.chars().next() {
                    if c.is_alphabetic() || c == '_' {
                        s.clone()
                    } else {
                        return Err(format!("Line {}: Expected identifier, found {:?}", tok.line, tok.kind));
                    }
                } else {
                    return Err(format!("Line {}: Expected identifier, found {:?}", tok.line, tok.kind));
                }
            }
        };
        self.advance();
        Ok(name)
    }

    fn parse_impl_block(&mut self) -> Result<ImplBlock, String> {
        let name_tok = self.peek().clone();
        let target_type = match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); s.clone() },
            TokenKind::StringTy => { self.advance(); "String".into() },
            TokenKind::VecTy => { self.advance(); "Vec".into() },
            TokenKind::File => { self.advance(); "File".into() },
            _ => return Err(format!("Line {}: Expected type name after impl, got {:?}", name_tok.line, name_tok.kind)),
        };
        let span = Span { line: name_tok.line, col: name_tok.col };

        // Optional generic params: impl<T> TypeName { ... }
        let mut generic_params = Vec::new();
        if self.match_token(TokenKind::Lt) {
            while !self.check(TokenKind::Gt) && !self.check(TokenKind::Eof) {
                let p_tok = self.peek().clone();
                let p_name = match &p_tok.kind {
                    TokenKind::Ident(s) => { self.advance(); s.clone() },
                    _ => return Err(format!("Line {}: Expected generic parameter name", p_tok.line)),
                };
                generic_params.push(GenericParam {
                    name: p_name,
                    span: Span { line: p_tok.line, col: p_tok.col },
                });
                if !self.match_token(TokenKind::Comma) { break; }
            }
            self.expect(TokenKind::Gt, "'>' to close generic parameters")?;
        }

        self.expect(TokenKind::LBrace, "'{' to begin impl body")?;
        let mut methods = Vec::new();
        while !self.check(TokenKind::RBrace) && !self.check(TokenKind::Eof) {
            // Optional pub keyword
            let _is_pub = self.match_token(TokenKind::Pub);
            let mut is_safe = true;
            if self.match_token(TokenKind::AtUnsafe) {
                is_safe = false;
            } else if self.match_token(TokenKind::AtSafe) {
                is_safe = true;
            }
            self.expect(TokenKind::Fn, "'fn' in impl block")?;
            let f = self.parse_func_decl(is_safe)?;
            methods.push(f);
        }
        self.expect(TokenKind::RBrace, "'}' to end impl body")?;
        Ok(ImplBlock { target_type, generic_params, methods, span })
    }

    fn parse_func_decl(&mut self, is_safe: bool) -> Result<FuncDecl, String> {
        let name_tok = self.peek().clone();
        let name = match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); s.clone() },
            _ => return Err(format!("Expected fn name, found {:?}", name_tok.kind))
        };
        let span = Span { line: name_tok.line, col: name_tok.col };

        self.expect(TokenKind::LParen, "'('")?;
        let mut params = Vec::new();
        while !self.check(TokenKind::RParen) {
            let p_name_tok = self.peek().clone();
            let p_name = match &p_name_tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                _ => return Err("Expected param name".into())
            };
            self.expect(TokenKind::Colon, "':'")?;
            let ty = self.parse_type()?;
            params.push(Param {
                name: p_name, ty, span: Span { line: p_name_tok.line, col: p_name_tok.col },
            });
            if !self.match_token(TokenKind::Comma) { break; }
        }
        self.expect(TokenKind::RParen, "')'")?;

        let mut ret_ty = None;
        if self.match_token(TokenKind::Arrow) {
            ret_ty = Some(self.parse_type()?);
        }

        let body = self.parse_block()?;
        Ok(FuncDecl { name, is_safe, params, ret_ty, body, span })
    }

    // ── Kernel ──────────────────────────────────────────────

    fn parse_kernel(&mut self, target: Option<HardwareTarget>) -> Result<KernelDecl, String> {
        let name_tok = self.peek().clone();
        let name = match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); s.clone() },
            _ => return Err(format!("Expected kernel name, found {:?}", name_tok.kind))
        };

        let span = Span { line: name_tok.line, col: name_tok.col };

        self.expect(TokenKind::LParen, "'(' to start kernel parameters")?;
        let mut params = Vec::new();
        while !self.check(TokenKind::RParen) {
            let p_name_tok = self.peek().clone();
            let p_name = match &p_name_tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                TokenKind::RoleA => { self.advance(); "A".into() },
                TokenKind::RoleB => { self.advance(); "B".into() },
                TokenKind::RoleC => { self.advance(); "C".into() },
                TokenKind::RoleD => { self.advance(); "D".into() },
                _ => return Err(format!("Expected parameter name, found {:?}", p_name_tok.kind))
            };

            self.expect(TokenKind::Colon, "':' after parameter name")?;
            let ty = self.parse_type()?;

            params.push(Param {
                name: p_name,
                ty,
                span: Span { line: p_name_tok.line, col: p_name_tok.col },
            });

            if !self.match_token(TokenKind::Comma) {
                break;
            }
        }
        self.expect(TokenKind::RParen, "')' to end kernel parameters")?;

        let body = self.parse_block()?;

        Ok(KernelDecl { target, name, params, body, span })
    }

    // ── Blocks and Statements ───────────────────────────────

    fn parse_block(&mut self) -> Result<Block, String> {
        let tok = self.expect(TokenKind::LBrace, "'{' to begin block")?;
        let span = Span { line: tok.line, col: tok.col };

        let mut stmts = Vec::new();
        while !self.check(TokenKind::RBrace) && !self.check(TokenKind::Eof) {
            stmts.push(self.parse_stmt()?);
        }

        self.expect(TokenKind::RBrace, "'}' to end block")?;
        Ok(Block { stmts, span })
    }

    fn parse_stmt(&mut self) -> Result<Stmt, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };

        // Attributes applied to types/stmts (like cache_policy)
        let mut cache_policy = None;
        if self.match_token(TokenKind::AtCachePolicy) {
            self.expect(TokenKind::LParen, "'('")?;
            let mut p_name = "".to_string();
            
            // Allow matching CachePolicy token
            let pt_tok = self.peek().clone();
            match &pt_tok.kind {
                TokenKind::L2Persist => { p_name = "L2_PERSIST".into(); self.advance(); },
                TokenKind::L2EvictFirst => { p_name = "L2_EVICT_FIRST".into(); self.advance(); },
                TokenKind::L2EvictLast => { p_name = "L2_EVICT_LAST".into(); self.advance(); },
                TokenKind::L2Stream => { p_name = "L2_STREAM".into(); self.advance(); },
                _ => return Err("Expected a valid Cache Policy identifier".into()),
            }

            let mut reuse = None;
            if self.match_token(TokenKind::Comma) {
                let id = self.peek().clone();
                if let TokenKind::Ident(k) = id.kind {
                    if k == "reuse_count" {
                        self.advance();
                        self.expect(TokenKind::Assign, "'='")?;
                        let v = self.peek().clone();
                        if let TokenKind::IntLit(val) = v.kind {
                            reuse = Some(val);
                            self.advance();
                        }
                    }
                }
            }
            self.expect(TokenKind::RParen, "')'")?;
            cache_policy = Some(CachePolicyAttr { policy: p_name, reuse_count: reuse, span: Span{line:pt_tok.line, col:pt_tok.col} });
        }

        if self.match_token(TokenKind::Let) {
            let mutable = self.match_token(TokenKind::Mut);
            let ident_tok = self.peek().clone();
            let name = match &ident_tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                _ => return Err(format!("Line {}: Expected identifier after let", ident_tok.line))
            };
            
            let mut ty = None;
            if self.match_token(TokenKind::Colon) {
                ty = Some(self.parse_type()?);
            }

            let mut init = None;
            if self.match_token(TokenKind::Assign) {
                init = Some(self.parse_expr()?);
            }
            self.expect(TokenKind::Semicolon, "';' at end of let statement")?;
            Ok(Stmt::Let { name, ty, init, cache_policy, span })

        } else if self.match_token(TokenKind::Type) {
            let ident_tok = self.peek().clone();
            let name = match &ident_tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                _ => return Err("Expected type alias name".into())
            };
            self.expect(TokenKind::Assign, "'=' in type alias")?;
            let ty = self.parse_type()?;
            self.expect(TokenKind::Semicolon, "';' at end of type alias")?;
            Ok(Stmt::TypeAlias { name, ty, span })

        } else if self.match_token(TokenKind::Return) {
            let mut val = None;
            if !self.check(TokenKind::Semicolon) {
                val = Some(self.parse_expr()?);
            }
            self.expect(TokenKind::Semicolon, "';' after return statement")?;
            Ok(Stmt::Return(val, span))

        } else if self.match_token(TokenKind::For) {
            let id = self.peek().clone();
            let loop_var = match &id.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() },
                _ => return Err("Expected loop variable".into())
            };
            self.expect(TokenKind::In, "'in'")?;
            
            let start = self.parse_primary_expr()?;
            self.expect(TokenKind::DotDot, "'..'")?;
            let end = self.parse_primary_expr()?;
            
            let mut step = None;
            if self.match_token(TokenKind::Step) {
                step = Some(self.parse_primary_expr()?);
            }

            let body = self.parse_block()?;
            Ok(Stmt::For { loop_var, start, end, step, body, span })

        } else if self.match_token(TokenKind::Chisel) {
            let block = self.parse_block()?;
            Ok(Stmt::Chisel(block, span))

        } else if self.match_token(TokenKind::If) {
            let condition = Box::new(self.parse_expr()?);
            let then_block = self.parse_block()?;
            let else_block = if self.match_token(TokenKind::Else) {
                if self.check(TokenKind::If) {
                    // else if: wrap in a block containing a single If stmt
                    let elif_stmt = self.parse_stmt()?;
                    let s = elif_stmt.span();
                    Some(Block { stmts: vec![elif_stmt], span: s })
                } else {
                    Some(self.parse_block()?)
                }
            } else {
                None
            };
            Ok(Stmt::If { condition, then_block, else_block, span })

        } else if self.match_token(TokenKind::While) {
            let condition = Box::new(self.parse_expr()?);
            let body = self.parse_block()?;
            Ok(Stmt::While { condition, body, span })

        } else if self.match_token(TokenKind::Match) {
            let scrutinee = Box::new(self.parse_expr()?);
            self.expect(TokenKind::LBrace, "'{' to begin match body")?;
            let mut arms = Vec::new();
            while !self.check(TokenKind::RBrace) && !self.check(TokenKind::Eof) {
                let arm = self.parse_match_arm()?;
                arms.push(arm);
                self.match_token(TokenKind::Comma);
            }
            self.expect(TokenKind::RBrace, "'}' to end match body")?;
            Ok(Stmt::Match { scrutinee, arms, span })

        } else {
            // Must be Assignment, CompoundAssign, or Expr stmt
            let expr = self.parse_expr()?;
            if self.match_token(TokenKind::Assign) {
                let value = self.parse_expr()?;
                self.expect(TokenKind::Semicolon, "';'")?;
                Ok(Stmt::Assign { target: expr, value, span })
            } else if let Some(op) = self.peek_compound_assign_op() {
                self.advance(); // consume the compound operator
                let value = self.parse_expr()?;
                self.expect(TokenKind::Semicolon, "';'")?;
                Ok(Stmt::CompoundAssign { target: expr, op, value, span })
            } else {
                self.expect(TokenKind::Semicolon, "';' at end of expression")?;
                Ok(Stmt::Expr(expr))
            }
        }
    }

    fn peek_compound_assign_op(&self) -> Option<BinaryOp> {
        match &self.peek().kind {
            TokenKind::PlusAssign => Some(BinaryOp::Add),
            TokenKind::MinusAssign => Some(BinaryOp::Sub),
            TokenKind::StarAssign => Some(BinaryOp::Mul),
            TokenKind::SlashAssign => Some(BinaryOp::Div),
            _ => None,
        }
    }

    fn parse_match_arm(&mut self) -> Result<MatchArm, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };
        let pattern = self.parse_match_pattern()?;
        self.expect(TokenKind::FatArrow, "'=>' in match arm")?;
        let body = self.parse_expr()?;
        Ok(MatchArm { pattern, body, span })
    }

    fn parse_match_pattern(&mut self) -> Result<MatchPattern, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };
        match &tok.kind {
            TokenKind::IntLit(_) | TokenKind::FloatLit(_) | TokenKind::StringLit(_) => {
                let lit = self.parse_primary_expr()?;
                Ok(MatchPattern::Literal(lit))
            }
            TokenKind::True => { self.advance(); Ok(MatchPattern::Literal(Expr::BoolLit(true, span))) }
            TokenKind::False => { self.advance(); Ok(MatchPattern::Literal(Expr::BoolLit(false, span))) }
            _ => {
                // Try wildcard '_'
                if let TokenKind::Ident(s) = &tok.kind {
                    if s == "_" {
                        self.advance();
                        return Ok(MatchPattern::Wildcard(span));
                    }
                }
                // Named pattern or enum variant
                let name = self.parse_any_ident()?;
                if self.match_token(TokenKind::ColonColon) {
                    let variant = self.parse_any_ident()?;
                    let mut bindings = Vec::new();
                    if self.match_token(TokenKind::LParen) {
                        while !self.check(TokenKind::RParen) && !self.check(TokenKind::Eof) {
                            let b = self.parse_any_ident()?;
                            bindings.push(b);
                            if !self.match_token(TokenKind::Comma) { break; }
                        }
                        self.expect(TokenKind::RParen, "')' after match bindings")?;
                    }
                    Ok(MatchPattern::EnumVariant { path: name, variant, bindings, span })
                } else if self.match_token(TokenKind::LParen) {
                    // Simple enum variant: Variant(binding)
                    let mut bindings = Vec::new();
                    while !self.check(TokenKind::RParen) && !self.check(TokenKind::Eof) {
                        let b = self.parse_any_ident()?;
                        bindings.push(b);
                        if !self.match_token(TokenKind::Comma) { break; }
                    }
                    self.expect(TokenKind::RParen, "')' after match bindings")?;
                    Ok(MatchPattern::EnumVariant { path: String::new(), variant: name, bindings, span })
                } else {
                    Ok(MatchPattern::Ident(name, span))
                }
            }
        }
    }

    // ── Types ───────────────────────────────────────────────

    fn parse_type(&mut self) -> Result<Type, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };

        // Array type: [T; SIZE]
        if self.match_token(TokenKind::LBracket) {
            let element = self.parse_type()?;
            self.expect(TokenKind::Semicolon, "';' in array type [T; SIZE]")?;
            let size = self.parse_primary_expr()?;
            self.expect(TokenKind::RBracket, "']' to close array type")?;
            return Ok(Type::Array { element: Box::new(element), size: Box::new(size), span });
        }

        // Reference type: &T or &mut T
        if self.match_token(TokenKind::Ampersand) {
            let mutable = self.match_token(TokenKind::Mut);
            let inner = self.parse_type()?;
            return Ok(Type::Reference { mutable, inner: Box::new(inner), span });
        }

        // Extract base name
        let base_name = match &tok.kind {
            TokenKind::GlobalMemory => { self.advance(); "GlobalMemory".to_string() }
            TokenKind::SharedMemory => { self.advance(); "SharedMemory".to_string() }
            TokenKind::L2Memory => { self.advance(); "L2Memory".to_string() }
            TokenKind::RegisterFile => { self.advance(); "RegisterFile".to_string() }
            TokenKind::SmemLayout => { self.advance(); "SmemLayout".to_string() }
            TokenKind::Swizzle => { self.advance(); "Swizzle".to_string() }
            TokenKind::Pipeline => { self.advance(); "Pipeline".to_string() }
            TokenKind::Transfer => { self.advance(); "Transfer".to_string() }
            TokenKind::Fragment => { self.advance(); "Fragment".to_string() }
            TokenKind::Async => { self.advance(); "Async".to_string() }
            TokenKind::Sync => { self.advance(); "Sync".to_string() }
            TokenKind::F16 => { self.advance(); return Ok(Type::Primitive("F16".into(), span)); }
            TokenKind::F32 => { self.advance(); return Ok(Type::Primitive("F32".into(), span)); }
            TokenKind::F64 => { self.advance(); return Ok(Type::Primitive("F64".into(), span)); }
            TokenKind::I8 => { self.advance(); return Ok(Type::Primitive("I8".into(), span)); }
            TokenKind::I16 => { self.advance(); return Ok(Type::Primitive("I16".into(), span)); }
            TokenKind::I32 => { self.advance(); return Ok(Type::Primitive("I32".into(), span)); }
            TokenKind::I64 => { self.advance(); return Ok(Type::Primitive("I64".into(), span)); }
            TokenKind::U8 => { self.advance(); return Ok(Type::Primitive("U8".into(), span)); }
            TokenKind::U16 => { self.advance(); return Ok(Type::Primitive("U16".into(), span)); }
            TokenKind::U32 => { self.advance(); return Ok(Type::Primitive("U32".into(), span)); }
            TokenKind::U64 => { self.advance(); return Ok(Type::Primitive("U64".into(), span)); }
            TokenKind::Bool => { self.advance(); return Ok(Type::Primitive("bool".into(), span)); }
            TokenKind::RoleA => { self.advance(); return Ok(Type::Ident("A".into(), span)); }
            TokenKind::RoleB => { self.advance(); return Ok(Type::Ident("B".into(), span)); }
            TokenKind::RoleC => { self.advance(); return Ok(Type::Ident("C".into(), span)); }
            TokenKind::RoleD => { self.advance(); return Ok(Type::Ident("D".into(), span)); }
            TokenKind::StringTy => { self.advance(); return Ok(Type::Primitive("String".into(), span)); }
            TokenKind::CharTy => { self.advance(); return Ok(Type::Primitive("char".into(), span)); }
            TokenKind::VecTy => { self.advance(); "Vec".to_string() }
            TokenKind::File => { self.advance(); "File".to_string() }
            TokenKind::OptionTy => { self.advance(); "Option".to_string() }
            TokenKind::Ident(s) => { self.advance(); s.clone() }
            TokenKind::MmaMod(s) => { self.advance(); s.clone() }
            _ => return Err(format!("Line {}: Expected type identifier, found {:?}", tok.line, tok.kind))
        };

        // Generics parsing: < ... >
        if self.match_token(TokenKind::Lt) {
            let mut args = Vec::new();
            while !self.check(TokenKind::Gt) {
                // If it's Named arguments like `rows=16`
                if let TokenKind::Ident(k) = &self.peek().kind {
                    // Check if next token is `=`
                    if self.tokens[self.pos + 1].kind == TokenKind::Assign {
                        let name = k.clone();
                        self.advance(); // consume ident
                        self.advance(); // consume '='
                        // Parsing value expression (assuming basic literal for now)
                        let val = self.parse_primary_expr()?;
                        args.push(GenericArg::Named { name, val });
                    } else {
                        // It's a standard type argument
                        let ty_arg = self.parse_type()?;
                        args.push(GenericArg::Type(ty_arg));
                    }
                } else if matches!(self.peek().kind, TokenKind::IntLit(_)) {
                    // Constant generic value like `3` or `128`
                    let val = self.parse_primary_expr()?;
                    args.push(GenericArg::Value(val));
                } else {
                     let ty_arg = self.parse_type()?;
                     args.push(GenericArg::Type(ty_arg));
                }

                if !self.match_token(TokenKind::Comma) {
                    break;
                }
            }
            self.expect(TokenKind::Gt, "'>'")?;
            Ok(Type::Generic { base: base_name, args, span })
        } else {
            Ok(Type::Ident(base_name, span))
        }
    }

    // ── Expressions (Pratt parser with precedence climbing) ──

    fn parse_expr(&mut self) -> Result<Expr, String> {
        self.parse_expr_bp(0)
    }

    /// Pratt parser: parse expression with minimum binding power.
    /// Binding powers (left, right) — left-associative: l_bp = r_bp - 1
    ///   ||          :  1,  2
    ///   &&          :  3,  4
    ///   == !=       :  5,  6
    ///   < > <= >=   :  7,  8
    ///   | ^         :  9, 10
    ///   &           : 11, 12
    ///   << >>       : 13, 14
    ///   + -         : 15, 16
    ///   * / %       : 17, 18
    fn parse_expr_bp(&mut self, min_bp: u8) -> Result<Expr, String> {
        // Parse prefix (unary operators) or primary
        let mut lhs = self.parse_unary_or_primary()?;

        loop {
            // Try postfix operations (highest precedence: call, index, member access)
            let had_postfix = self.try_parse_postfix(&mut lhs)?;
            if had_postfix { continue; }

            // Try binary operator
            if let Some((op, l_bp, r_bp)) = self.peek_binary_op() {
                if l_bp < min_bp {
                    break;
                }
                self.advance(); // consume operator token
                let span = lhs.span();
                let rhs = self.parse_expr_bp(r_bp)?;
                lhs = Expr::BinaryOp {
                    left: Box::new(lhs),
                    op,
                    right: Box::new(rhs),
                    span,
                };
                continue;
            }

            break;
        }

        Ok(lhs)
    }

    /// Map current token to binary operator + binding powers, if applicable.
    fn peek_binary_op(&self) -> Option<(BinaryOp, u8, u8)> {
        match &self.peek().kind {
            // Logical
            TokenKind::PipePipe  => Some((BinaryOp::Or,     1,  2)),
            TokenKind::AmpAmp   => Some((BinaryOp::And,     3,  4)),
            // Equality
            TokenKind::EqEq     => Some((BinaryOp::Eq,      5,  6)),
            TokenKind::NotEq    => Some((BinaryOp::NotEq,   5,  6)),
            // Comparison
            TokenKind::LtEq     => Some((BinaryOp::Le,      7,  8)),
            TokenKind::GtEq     => Some((BinaryOp::Ge,      7,  8)),
            // Lt/Gt: only treat as comparison if NOT followed by potential generic args
            TokenKind::Lt       => {
                // Heuristic: if LHS was an Ident/Path and this looks like a generic call,
                // don't treat as binary op — let postfix handle it.
                // In the Pratt loop, postfix is tried first, so if we reach here
                // it means postfix didn't consume it, so it IS a comparison.
                Some((BinaryOp::Lt, 7, 8))
            }
            TokenKind::Gt       => Some((BinaryOp::Gt,      7,  8)),
            // Bitwise
            TokenKind::Pipe     => Some((BinaryOp::BitOr,   9, 10)),
            TokenKind::Caret    => Some((BinaryOp::BitXor,  9, 10)),
            TokenKind::Ampersand=> Some((BinaryOp::BitAnd, 11, 12)),
            TokenKind::LtLt     => Some((BinaryOp::Shl,    13, 14)),
            TokenKind::GtGt     => Some((BinaryOp::Shr,    13, 14)),
            // Arithmetic
            TokenKind::Plus     => Some((BinaryOp::Add,    15, 16)),
            TokenKind::Minus    => Some((BinaryOp::Sub,    15, 16)),
            TokenKind::Star     => Some((BinaryOp::Mul,    17, 18)),
            TokenKind::Slash    => Some((BinaryOp::Div,    17, 18)),
            TokenKind::Percent  => Some((BinaryOp::Mod,    17, 18)),
            _ => None,
        }
    }

    /// Try to parse a postfix operation. Returns true if one was consumed.
    fn try_parse_postfix(&mut self, lhs: &mut Expr) -> Result<bool, String> {
        let span = lhs.span();

        if self.match_token(TokenKind::LParen) {
            // Function call
            let mut args = Vec::new();
            while !self.check(TokenKind::RParen) {
                args.push(self.parse_expr()?);
                if !self.match_token(TokenKind::Comma) { break; }
            }
            self.expect(TokenKind::RParen, "')'")?;
            *lhs = Expr::Call { func: Box::new(lhs.clone()), args, span };
            return Ok(true);
        }

        if self.match_token(TokenKind::LBracket) {
            // Indexing
            let index = self.parse_expr()?;
            self.expect(TokenKind::RBracket, "']'")?;
            *lhs = Expr::Index { base: Box::new(lhs.clone()), index: Box::new(index), span };
            return Ok(true);
        }

        if self.match_token(TokenKind::Dot) {
            // Member access
            let tok = self.peek().clone();
            let member = match &tok.kind {
                TokenKind::Ident(s) => { self.advance(); s.clone() }
                TokenKind::Wait => { self.advance(); "wait".into() }
                TokenKind::Sync => { self.advance(); "sync".into() }
                TokenKind::Load => { self.advance(); "load".into() }
                TokenKind::Store => { self.advance(); "store".into() }
                _ => return Err(format!("Line {}: Expected identifier after '.'", tok.line)),
            };
            *lhs = Expr::MemberAccess { base: Box::new(lhs.clone()), member, span };
            return Ok(true);
        }

        if self.match_token(TokenKind::Arrow) {
            // Return/store syntax `acc -> C`
            let tok = self.peek().clone();
            if let TokenKind::Ident(s) = tok.kind {
                self.advance();
                *lhs = Expr::Path { namespace: format!("{:?}", lhs), member: s, span };
                return Ok(true);
            }
        }

        // Generic call: only attempt if LHS is Ident/Path and next is `<`
        if self.check(TokenKind::Lt) {
            let is_generic_candidate = matches!(lhs, Expr::Ident(..) | Expr::Path { .. });
            if is_generic_candidate {
                let saved_pos = self.pos;
                self.advance(); // consume '<'
                // Try parsing as generic call — if it fails, backtrack
                match self.try_parse_generic_args() {
                    Ok((types, args)) => {
                        *lhs = Expr::GenericCall {
                            func: Box::new(lhs.clone()),
                            generic_args: types,
                            args,
                            span,
                        };
                        return Ok(true);
                    }
                    Err(_) => {
                        // Backtrack: not a generic call, it's a comparison operator
                        self.pos = saved_pos;
                    }
                }
            }
        }

        Ok(false)
    }

    /// Try to parse generic args and following call args: `<Type, Type>(args)`
    fn try_parse_generic_args(&mut self) -> Result<(Vec<Type>, Vec<Expr>), String> {
        let mut types = Vec::new();
        while !self.check(TokenKind::Gt) {
            types.push(self.parse_type()?);
            if !self.match_token(TokenKind::Comma) { break; }
        }
        self.expect(TokenKind::Gt, "'>'")?;
        self.expect(TokenKind::LParen, "'('")?;
        let mut args = Vec::new();
        while !self.check(TokenKind::RParen) {
            args.push(self.parse_expr()?);
            if !self.match_token(TokenKind::Comma) { break; }
        }
        self.expect(TokenKind::RParen, "')'")?;
        Ok((types, args))
    }

    /// Parse unary prefix operators or fall through to primary expression.
    fn parse_unary_or_primary(&mut self) -> Result<Expr, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };

        // Unary minus: -expr
        if self.match_token(TokenKind::Minus) {
            let operand = self.parse_expr_bp(19)?; // higher than any binary op
            return Ok(Expr::UnaryOp { op: UnaryOp::Neg, operand: Box::new(operand), span });
        }

        // Unary not: !expr
        if self.match_token(TokenKind::Bang) {
            let operand = self.parse_expr_bp(19)?;
            return Ok(Expr::UnaryOp { op: UnaryOp::Not, operand: Box::new(operand), span });
        }

        // Reference: &expr or &mut — but only in expression context, NOT type context
        // (Type references are handled in parse_type)

        // Dereference: *expr
        if self.match_token(TokenKind::Star) {
            let operand = self.parse_expr_bp(19)?;
            return Ok(Expr::UnaryOp { op: UnaryOp::Deref, operand: Box::new(operand), span });
        }
        
        // Address-of: &expr or &mut expr
        if self.match_token(TokenKind::Ampersand) {
            let _mutable = self.match_token(TokenKind::Mut);
            let operand = self.parse_expr_bp(19)?;
            return Ok(Expr::UnaryOp { op: UnaryOp::Ref, operand: Box::new(operand), span });
        }

        // Parenthesized expression: (expr)
        if self.match_token(TokenKind::LParen) {
            let inner = self.parse_expr()?;
            self.expect(TokenKind::RParen, "')' to close parenthesized expression")?;
            return Ok(inner);
        }

        self.parse_primary_expr()
    }

    fn parse_primary_expr(&mut self) -> Result<Expr, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };

        match &tok.kind {
            // Literals
            TokenKind::IntLit(v) => { self.advance(); Ok(Expr::IntLit(*v, span)) },
            TokenKind::FloatLit(v) => { self.advance(); Ok(Expr::FloatLit(*v, span)) },
            TokenKind::StringLit(s) => { self.advance(); Ok(Expr::StringLit(s.clone(), span)) },
            TokenKind::CharLit(c) => { self.advance(); Ok(Expr::CharLit(*c, span)) },
            TokenKind::True => { self.advance(); Ok(Expr::BoolLit(true, span)) },
            TokenKind::False => { self.advance(); Ok(Expr::BoolLit(false, span)) },
            TokenKind::SelfKw => { self.advance(); Ok(Expr::SelfLit(span)) },
            _ => {
                if let Ok(name) = self.parse_any_ident() {
                    // Try to parse namespace path like `String::clone`
                    if self.match_token(TokenKind::ColonColon) {
                        if let Ok(member) = self.parse_any_ident() {
                            return Ok(Expr::Path { namespace: name, member, span });
                        } else {
                            let unexpected = self.peek();
                            return Err(format!("Line {}: Expected member identifier after '::', found {:?}", unexpected.line, unexpected.kind));
                        }
                    } else {
                        return Ok(Expr::Ident(name, span));
                    }
                }
                return Err(format!("Line {}: Expected expression, found {:?}", tok.line, tok.kind));
            },
            // Type-like identifiers that can appear in expression position
            TokenKind::Fragment => {
                 self.advance();
                 if self.match_token(TokenKind::ColonColon) {
                     let next = self.peek().clone();
                     if let TokenKind::Ident(n) = &next.kind {
                        self.advance();
                        return Ok(Expr::Path { namespace: "Fragment".into(), member: n.clone(), span });
                     }
                 }
                 Ok(Expr::Ident("Fragment".into(), span))
            },
            TokenKind::Pipeline => {
                 self.advance();
                 if self.match_token(TokenKind::ColonColon) {
                     let next = self.peek().clone();
                     if let TokenKind::Ident(n) = &next.kind {
                        self.advance();
                        return Ok(Expr::Path { namespace: "Pipeline".into(), member: n.clone(), span });
                     }
                 }
                 Ok(Expr::Ident("Pipeline".into(), span))
            },
            TokenKind::SharedMemory => {
                 self.advance();
                 if self.match_token(TokenKind::ColonColon) {
                     let next = self.peek().clone();
                     if let TokenKind::Ident(n) = &next.kind {
                        self.advance();
                        return Ok(Expr::Path { namespace: "SharedMemory".into(), member: n.clone(), span });
                     }
                 }
                 Ok(Expr::Ident("SharedMemory".into(), span))
            },
            TokenKind::File => {
                 self.advance();
                 if self.match_token(TokenKind::ColonColon) {
                     let next = self.peek().clone();
                     if let TokenKind::Ident(n) = &next.kind {
                        self.advance();
                        return Ok(Expr::Path { namespace: "File".into(), member: n.clone(), span });
                     }
                 }
                 Ok(Expr::Ident("File".into(), span))
            },
            _ => Err(format!("Line {}: Expected expression, found {:?}", tok.line, tok.kind))
        }
    }

    // ── Import Declarations ─────────────────────────────────

    fn parse_import(&mut self) -> Result<ImportDecl, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };
        let mut path = Vec::new();

        // First segment
        let name_tok = self.peek().clone();
        match &name_tok.kind {
            TokenKind::Ident(s) => { self.advance(); path.push(s.clone()); },
            _ => return Err(format!("Line {}: Expected module path after import", name_tok.line)),
        }

        // Subsequent segments separated by '.'
        while self.match_token(TokenKind::Dot) {
            let seg_tok = self.peek().clone();
            match &seg_tok.kind {
                TokenKind::Ident(s) => { self.advance(); path.push(s.clone()); },
                _ => return Err(format!("Line {}: Expected identifier in import path", seg_tok.line)),
            }
        }

        self.expect(TokenKind::Semicolon, "';' after import declaration")?;
        Ok(ImportDecl { path, span })
    }

    // ── Static Assert ───────────────────────────────────────

    fn parse_static_assert(&mut self) -> Result<StaticAssertDecl, String> {
        let tok = self.peek().clone();
        let span = Span { line: tok.line, col: tok.col };

        self.expect(TokenKind::LParen, "'(' after @static_assert")?;
        let condition = self.parse_expr()?;
        self.expect(TokenKind::Comma, "',' separating condition and message in @static_assert")?;

        let msg_tok = self.peek().clone();
        let message = match &msg_tok.kind {
            TokenKind::StringLit(s) => { self.advance(); s.clone() },
            _ => return Err(format!("Line {}: Expected string message in @static_assert", msg_tok.line)),
        };

        self.expect(TokenKind::RParen, "')' to close @static_assert")?;
        self.expect(TokenKind::Semicolon, "';' after @static_assert")?;
        Ok(StaticAssertDecl { condition, message, span })
    }
}
