/* ============================================== */
/*  Generated by Y-Lang Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y-Lang Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y-Lang Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y-Lang Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y-Lang Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


typedef enum {
    MyEnum_TAG_A,
    MyEnum_TAG_B
} MyEnum_Tag;

typedef struct {
    int32_t _0;
} MyEnum_A_Data;

typedef struct {
    MyEnum_Tag tag;
    union {
        MyEnum_A_Data A;
    } data;
} MyEnum;

static inline MyEnum MyEnum_A(int32_t _0) {
    MyEnum res;
    res.tag = MyEnum_TAG_A;
    res.data.A._0 = _0;
    return res;
}

#define MyEnum_B ((MyEnum){ .tag = MyEnum_TAG_B })
void test(MyEnum e);

void test(MyEnum e) {
}

