; ================================================
;  Generated by Y-Lang Compiler — LLVM IR Backend
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

; --- Struct Definitions ---

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [30 x i8] c"--- Y-Lang Execution Test ---\00"
@.str.1 = private unnamed_addr constant [31 x i8] c"Calculating Fibonacci of 10...\00"
@.str.2 = private unnamed_addr constant [8 x i8] c"Result:\00"
@.str.3 = private unnamed_addr constant [1 x i8] c"\00"
@.str.4 = private unnamed_addr constant [55 x i8] c"Y-Lang to Native LLVM compilation is fully functional!\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define i32 @fibonacci(i32 %n.arg) {
entry:
  %n = alloca i32
  store i32 %n.arg, ptr %n
  %t1 = load i32, ptr %n
  %t2 = icmp sle i32 %t1, 1
  br i1 %t2, label %then.1, label %merge.3
then.1:
  %t3 = load i32, ptr %n
  ret i32 %t3
merge.3:
  %t4 = load i32, ptr %n
  %t5 = sub i32 %t4, 1
  %t6 = call i32 @fibonacci(i32 %t5)
  %t7 = load i32, ptr %n
  %t8 = sub i32 %t7, 2
  %t9 = call i32 @fibonacci(i32 %t8)
  %t10 = add i32 %t6, %t9
  ret i32 %t10
}

define void @main() {
entry:
  %t1 = call ptr @ystr_new(ptr @.str.0)
  %t2 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t1)
  %t3 = call ptr @ystr_new(ptr @.str.1)
  %t4 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t3)
  %result = alloca i32
  %t5 = call i32 @fibonacci(i32 10)
  store i32 %t5, ptr %result
  %t6 = call ptr @ystr_new(ptr @.str.2)
  %t7 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t6)
  %t8 = load i32, ptr %result
  %t9 = call i32 (ptr, ...) @printf(ptr @.fmt.d, i32 %t8)
  %t10 = call ptr @ystr_new(ptr @.str.3)
  %t11 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t10)
  %t12 = call ptr @ystr_new(ptr @.str.4)
  %t13 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t12)
  ret void
}

